DELIMITER $$
	CREATE TRIGGER COBERTURA_ENFERMEDADES_TRIGGER_UPDATE
	AFTER UPDATE ON COBERTURA_ENFERMEDADES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `COBERTURA_ENFERMEDADES_AUDIT`(`FECHA`,`ID`,`ID_ENFERMEDAD`,`INDICADOR`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.ID_ENFERMEDAD, NEW.INDICADOR, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER COBERTURA_ENFERMEDADES_TRIGGER_INSERT
	AFTER INSERT ON COBERTURA_ENFERMEDADES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `COBERTURA_ENFERMEDADES_AUDIT`(`FECHA`,`ID`,`ID_ENFERMEDAD`,`INDICADOR`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.ID_ENFERMEDAD, NEW.INDICADOR, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER COBERTURA_ENFERMEDADES_TRIGGER_DELETE
	AFTER DELETE ON COBERTURA_ENFERMEDADES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `COBERTURA_ENFERMEDADES_AUDIT`(`FECHA`,`ID`,`ID_ENFERMEDAD`,`INDICADOR`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.ID_ENFERMEDAD, OLD.INDICADOR, 'DELETE');
	END$$
DELIMITER ;