DELIMITER $$
	CREATE TRIGGER COBRADORES_TRIGGER_UPDATE
	AFTER UPDATE ON COBRADORES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `COBRADORES_AUDIT`(`FECHA`,`ID`,`DNI`,`APELLIDO`,`NOMBRE`,`DIRECCION`,`TELEFONO`,`EMAIL`,`SEXO`,`FECHA_NACIMIENTO`,`ID_LOCALIDAD`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.DNI, NEW.APELLIDO, NEW.NOMBRE, NEW.DIRECCION, NEW.TELEFONO, NEW.EMAIL, NEW.SEXO, NEW.FECHA_NACIMIENTO, NEW.ID_LOCALIDAD, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER COBRADORES_TRIGGER_INSERT
	AFTER INSERT ON COBRADORES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `COBRADORES_AUDIT`(`FECHA`,`ID`,`DNI`,`APELLIDO`,`NOMBRE`,`DIRECCION`,`TELEFONO`,`EMAIL`,`SEXO`,`FECHA_NACIMIENTO`,`ID_LOCALIDAD`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.DNI, NEW.APELLIDO, NEW.NOMBRE, NEW.DIRECCION, NEW.TELEFONO, NEW.EMAIL, NEW.SEXO, NEW.FECHA_NACIMIENTO, NEW.ID_LOCALIDAD, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER COBRADORES_TRIGGER_DELETE
	AFTER DELETE ON COBRADORES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `COBRADORES_AUDIT`(`FECHA`,`ID`,`DNI`,`APELLIDO`,`NOMBRE`,`DIRECCION`,`TELEFONO`,`EMAIL`,`SEXO`,`FECHA_NACIMIENTO`,`ID_LOCALIDAD`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.DNI, OLD.APELLIDO, OLD.NOMBRE, OLD.DIRECCION, OLD.TELEFONO, OLD.EMAIL, OLD.SEXO, OLD.FECHA_NACIMIENTO, OLD.ID_LOCALIDAD, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;