DELIMITER $$
	CREATE TRIGGER ENFERMEDADES_TRIGGER_UPDATE
	AFTER UPDATE ON ENFERMEDADES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ENFERMEDADES_AUDIT`(`FECHA`,`ID`,`DESCRIPCION`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.DESCRIPCION, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER ENFERMEDADES_TRIGGER_INSERT
	AFTER INSERT ON ENFERMEDADES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ENFERMEDADES_AUDIT`(`FECHA`,`ID`,`DESCRIPCION`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.DESCRIPCION, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER ENFERMEDADES_TRIGGER_DELETE
	AFTER DELETE ON ENFERMEDADES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ENFERMEDADES_AUDIT`(`FECHA`,`ID`,`DESCRIPCION`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.DESCRIPCION, 'DELETE');
	END$$
DELIMITER ;