DELIMITER $$
	CREATE TRIGGER ESTADOS_TRIGGER_UPDATE
	AFTER UPDATE ON ESTADOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ESTADOS_AUDIT`(`FECHA`,`ID`,`NRO_ESTADO`,`DESCRIPCION`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NRO_ESTADO, NEW.DESCRIPCION, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER ESTADOS_TRIGGER_INSERT
	AFTER INSERT ON ESTADOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ESTADOS_AUDIT`(`FECHA`,`ID`,`NRO_ESTADO`,`DESCRIPCION`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NRO_ESTADO, NEW.DESCRIPCION, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER ESTADOS_TRIGGER_DELETE
	AFTER DELETE ON ESTADOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ESTADOS_AUDIT`(`FECHA`,`ID`,`NRO_ESTADO`,`DESCRIPCION`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.NRO_ESTADO, OLD.DESCRIPCION, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;