DELIMITER $$
	CREATE TRIGGER IMPRESION_COMPROBANTES_TRIGGER_UPDATE
	AFTER UPDATE ON IMPRESION_COMPROBANTES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `IMPRESION_COMPROBANTES_AUDIT`(`FECHA`,`ID`,`ID_COMPROBANTE`,`ID_ADHERENTE`,`IMPORTE`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.ID_COMPROBANTE, NEW.ID_ADHERENTE, NEW.IMPORTE, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER IMPRESION_COMPROBANTES_TRIGGER_INSERT
	AFTER INSERT ON IMPRESION_COMPROBANTES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `IMPRESION_COMPROBANTES_AUDIT`(`FECHA`,`ID`,`ID_COMPROBANTE`,`ID_ADHERENTE`,`IMPORTE`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.ID_COMPROBANTE, NEW.ID_ADHERENTE, NEW.IMPORTE, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER IMPRESION_COMPROBANTES_TRIGGER_DELETE
	AFTER DELETE ON IMPRESION_COMPROBANTES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `IMPRESION_COMPROBANTES_AUDIT`(`FECHA`,`ID`,`ID_COMPROBANTE`,`ID_ADHERENTE`,`IMPORTE`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.ID_COMPROBANTE, OLD.ID_ADHERENTE, OLD.IMPORTE, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;