DELIMITER $$
	CREATE TRIGGER LOCALIDADES_TRIGGER_UPDATE
	AFTER UPDATE ON LOCALIDADES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `LOCALIDADES_AUDIT`(`FECHA`,`ID`,`NRO_LOCALIDAD`,`NOMBRE`,`CODIGO_POSTAL`,`ID_PROVINCIA`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NRO_LOCALIDAD, NEW.NOMBRE, NEW.CODIGO_POSTAL, NEW.ID_PROVINCIA, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER LOCALIDADES_TRIGGER_INSERT
	AFTER INSERT ON LOCALIDADES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `LOCALIDADES_AUDIT`(`FECHA`,`ID`,`NRO_LOCALIDAD`,`NOMBRE`,`CODIGO_POSTAL`,`ID_PROVINCIA`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NRO_LOCALIDAD, NEW.NOMBRE, NEW.CODIGO_POSTAL, NEW.ID_PROVINCIA, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER LOCALIDADES_TRIGGER_DELETE
	AFTER DELETE ON LOCALIDADES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `LOCALIDADES_AUDIT`(`FECHA`,`ID`,`NRO_LOCALIDAD`,`NOMBRE`,`CODIGO_POSTAL`,`ID_PROVINCIA`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.NRO_LOCALIDAD, OLD.NOMBRE, OLD.CODIGO_POSTAL, OLD.ID_PROVINCIA, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;