DELIMITER $$
	CREATE TRIGGER MOTIVOS_BAJA_TRIGGER_UPDATE
	AFTER UPDATE ON MOTIVOS_BAJA
	FOR EACH ROW
	BEGIN
	  INSERT INTO `MOTIVOS_BAJA_AUDIT`(`FECHA`,`ID`,`DESCRIPCION`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.DESCRIPCION, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER MOTIVOS_BAJA_TRIGGER_INSERT
	AFTER INSERT ON MOTIVOS_BAJA
	FOR EACH ROW
	BEGIN
	  INSERT INTO `MOTIVOS_BAJA_AUDIT`(`FECHA`,`ID`,`DESCRIPCION`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.DESCRIPCION, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER MOTIVOS_BAJA_TRIGGER_DELETE
	AFTER DELETE ON MOTIVOS_BAJA
	FOR EACH ROW
	BEGIN
	  INSERT INTO `MOTIVOS_BAJA_AUDIT`(`FECHA`,`ID`,`DESCRIPCION`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.DESCRIPCION, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;