DELIMITER $$
	CREATE TRIGGER OBRAS_SOCIALES_TRIGGER_UPDATE
	AFTER UPDATE ON OBRAS_SOCIALES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `OBRAS_SOCIALES_AUDIT`(`FECHA`,`ID`,`DESCRIPCION`,`TIENE_SEPELIO`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.DESCRIPCION, NEW.TIENE_SEPELIO, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER OBRAS_SOCIALES_TRIGGER_INSERT
	AFTER INSERT ON OBRAS_SOCIALES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `OBRAS_SOCIALES_AUDIT`(`FECHA`,`ID`,`DESCRIPCION`,`TIENE_SEPELIO`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.DESCRIPCION, NEW.TIENE_SEPELIO, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER OBRAS_SOCIALES_TRIGGER_DELETE
	AFTER DELETE ON OBRAS_SOCIALES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `OBRAS_SOCIALES_AUDIT`(`FECHA`,`ID`,`DESCRIPCION`,`TIENE_SEPELIO`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.DESCRIPCION, OLD.TIENE_SEPELIO, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;