DELIMITER $$
	CREATE TRIGGER PAGOS_TRIGGER_UPDATE
	AFTER UPDATE ON PAGOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `PAGOS_AUDIT`(`FECHA`,`ID`,`VALOR`,`ID_SOCIO`,`ID_COBRADOR`,`ID_COMPROBANTE`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.VALOR, NEW.ID_SOCIO, NEW.ID_COBRADOR, NEW.ID_COMPROBANTE, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER PAGOS_TRIGGER_INSERT
	AFTER INSERT ON PAGOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `PAGOS_AUDIT`(`FECHA`,`ID`,`VALOR`,`ID_SOCIO`,`ID_COBRADOR`,`ID_COMPROBANTE`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.VALOR, NEW.ID_SOCIO, NEW.ID_COBRADOR, NEW.ID_COMPROBANTE, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER PAGOS_TRIGGER_DELETE
	AFTER DELETE ON PAGOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `PAGOS_AUDIT`(`FECHA`,`ID`,`VALOR`,`ID_SOCIO`,`ID_COBRADOR`,`ID_COMPROBANTE`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.VALOR, OLD.ID_SOCIO, OLD.ID_COBRADOR, OLD.ID_COMPROBANTE, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;