DELIMITER $$
	CREATE TRIGGER PARAMETROS_EMPRESA_TRIGGER_UPDATE
	AFTER UPDATE ON PARAMETROS_EMPRESA
	FOR EACH ROW
	BEGIN
	  INSERT INTO `PARAMETROS_EMPRESA_AUDIT`(`FECHA`,`ID`,`NOMBRE`,`DIRECCION`,`CUIT`,`INICIO_ACTIVIDADES`,`CONDICION_IVA`,`CONDICION_IIBB`,`TELEFONO`,`EMAIL`,`ID_LOCALIDAD`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NOMBRE, NEW.DIRECCION, NEW.CUIT, NEW.INICIO_ACTIVIDADES, NEW.CONDICION_IVA, NEW.CONDICION_IIBB, NEW.TELEFONO, NEW.EMAIL, NEW.ID_LOCALIDAD, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER PARAMETROS_EMPRESA_TRIGGER_INSERT
	AFTER INSERT ON PARAMETROS_EMPRESA
	FOR EACH ROW
	BEGIN
	  INSERT INTO `PARAMETROS_EMPRESA_AUDIT`(`FECHA`,`ID`,`NOMBRE`,`DIRECCION`,`CUIT`,`INICIO_ACTIVIDADES`,`CONDICION_IVA`,`CONDICION_IIBB`,`TELEFONO`,`EMAIL`,`ID_LOCALIDAD`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NOMBRE, NEW.DIRECCION, NEW.CUIT, NEW.INICIO_ACTIVIDADES, NEW.CONDICION_IVA, NEW.CONDICION_IIBB, NEW.TELEFONO, NEW.EMAIL, NEW.ID_LOCALIDAD, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER PARAMETROS_EMPRESA_TRIGGER_DELETE
	AFTER DELETE ON PARAMETROS_EMPRESA
	FOR EACH ROW
	BEGIN
	  INSERT INTO `PARAMETROS_EMPRESA_AUDIT`(`FECHA`,`ID`,`NOMBRE`,`DIRECCION`,`CUIT`,`INICIO_ACTIVIDADES`,`CONDICION_IVA`,`CONDICION_IIBB`,`TELEFONO`,`EMAIL`,`ID_LOCALIDAD`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.NOMBRE, OLD.DIRECCION, OLD.CUIT, OLD.INICIO_ACTIVIDADES, OLD.CONDICION_IVA, OLD.CONDICION_IIBB, OLD.TELEFONO, OLD.EMAIL, OLD.ID_LOCALIDAD, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;