DELIMITER $$
	CREATE TRIGGER PLANES_TRIGGER_UPDATE
	AFTER UPDATE ON PLANES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `PLANES_AUDIT`(`FECHA`,`METODO`,`ID`,`NRO_PLAN`,`DESCRIPCION`,`ID_USUARIO_MODIFICA`)
	  VALUES (NOW(), 'UPDATE', NEW.ID, NEW.NRO_PLAN, NEW.DESCRIPCION, NEW.ID_USUARIO_MODIFICA);
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER PLANES_TRIGGER_INSERT
	AFTER INSERT ON PLANES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `PLANES_AUDIT`(`FECHA`,`METODO`,`ID`,`NRO_PLAN`,`DESCRIPCION`,`ID_USUARIO_MODIFICA`)
	  VALUES (NOW(), 'INSERT', NEW.ID, NEW.NRO_PLAN, NEW.DESCRIPCION, NEW.ID_USUARIO_MODIFICA);
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER PLANES_TRIGGER_DELETE
	AFTER DELETE ON PLANES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `PLANES_AUDIT`(`FECHA`,`METODO`,`ID`,`NRO_PLAN`,`DESCRIPCION`,`ID_USUARIO_MODIFICA`)
	  VALUES (NOW(), 'DELETE', OLD.ID, OLD.NRO_PLAN, OLD.DESCRIPCION, OLD.ID_USUARIO_MODIFICA);
	END$$
DELIMITER ;