DELIMITER $$
	CREATE TRIGGER PROVINCIAS_TRIGGER_UPDATE
	AFTER UPDATE ON PROVINCIAS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `PROVINCIAS_AUDIT`(`FECHA`,`ID`,`NOMBRE`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NOMBRE, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER PROVINCIAS_TRIGGER_INSERT
	AFTER INSERT ON PROVINCIAS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `PROVINCIAS_AUDIT`(`FECHA`,`ID`,`NOMBRE`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NOMBRE, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER PROVINCIAS_TRIGGER_DELETE
	AFTER DELETE ON PROVINCIAS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `PROVINCIAS_AUDIT`(`FECHA`,`ID`,`NOMBRE`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.NOMBRE, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;