DELIMITER $$
	CREATE TRIGGER RANGOS_TARIFAS_TRIGGER_UPDATE
	AFTER UPDATE ON RANGOS_TARIFAS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `RANGOS_TARIFAS_AUDIT`(`FECHA`,`ID`,`EDAD_DESDE`,`EDAD_HASTA`,`VALOR`,`ID_USUARIO_MODIFICA`,`ID_TARIFA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.EDAD_DESDE, NEW.EDAD_HASTA, NEW.VALOR, NEW.ID_USUARIO_MODIFICA, NEW.ID_TARIFA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER RANGOS_TARIFAS_TRIGGER_INSERT
	AFTER INSERT ON RANGOS_TARIFAS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `RANGOS_TARIFAS_AUDIT`(`FECHA`,`ID`,`EDAD_DESDE`,`EDAD_HASTA`,`VALOR`,`ID_USUARIO_MODIFICA`,`ID_TARIFA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.EDAD_DESDE, NEW.EDAD_HASTA, NEW.VALOR, NEW.ID_USUARIO_MODIFICA, NEW.ID_TARIFA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER RANGOS_TARIFAS_TRIGGER_DELETE
	AFTER DELETE ON RANGOS_TARIFAS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `RANGOS_TARIFAS_AUDIT`(`FECHA`,`ID`,`EDAD_DESDE`,`EDAD_HASTA`,`VALOR`,`ID_USUARIO_MODIFICA`,`ID_TARIFA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.EDAD_DESDE, OLD.EDAD_HASTA, OLD.VALOR, OLD.ID_USUARIO_MODIFICA, OLD.ID_TARIFA, 'DELETE');
	END$$
DELIMITER ;