DELIMITER $$
	CREATE TRIGGER SOCIOS_TRIGGER_UPDATE
	AFTER UPDATE ON SOCIOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `SOCIOS_AUDIT`(`FECHA`,`ID`,`DNI`,`APELLIDO`,`NOMBRE`,`DIRECCION`,`TELEFONO`,`EMAIL`,`SEXO`,`FECHA_NACIMIENTO`,`FECHA_COBERTURA`,`SALDO`,`ID_TARIFA`,`ID_ZONA`,`ID_LOCALIDAD`,`ID_OBRA_SOCIAL`,`ID_ESTADO`,`ID_USUARIO_MODIFICA`,`ID_ENFERMEDAD`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.DNI, NEW.APELLIDO, NEW.NOMBRE, NEW.DIRECCION, NEW.TELEFONO, NEW.EMAIL, NEW.SEXO, NEW.FECHA_NACIMIENTO, NEW.FECHA_COBERTURA, NEW.SALDO, NEW.ID_TARIFA, NEW.ID_ZONA, NEW.ID_LOCALIDAD, NEW.ID_OBRA_SOCIAL, NEW.ID_ESTADO, NEW.ID_USUARIO_MODIFICA, NEW.ID_ENFERMEDAD, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER SOCIOS_TRIGGER_INSERT
	AFTER INSERT ON SOCIOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `SOCIOS_AUDIT`(`FECHA`,`ID`,`DNI`,`APELLIDO`,`NOMBRE`,`DIRECCION`,`TELEFONO`,`EMAIL`,`SEXO`,`FECHA_NACIMIENTO`,`FECHA_COBERTURA`,`SALDO`,`ID_TARIFA`,`ID_ZONA`,`ID_LOCALIDAD`,`ID_OBRA_SOCIAL`,`ID_ESTADO`,`ID_USUARIO_MODIFICA`,`ID_ENFERMEDAD`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.DNI, NEW.APELLIDO, NEW.NOMBRE, NEW.DIRECCION, NEW.TELEFONO, NEW.EMAIL, NEW.SEXO, NEW.FECHA_NACIMIENTO, NEW.FECHA_COBERTURA, NEW.SALDO, NEW.ID_TARIFA, NEW.ID_ZONA, NEW.ID_LOCALIDAD, NEW.ID_OBRA_SOCIAL, NEW.ID_ESTADO, NEW.ID_USUARIO_MODIFICA, NEW.ID_ENFERMEDAD, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER SOCIOS_TRIGGER_DELETE
	AFTER DELETE ON SOCIOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `SOCIOS_AUDIT`(`FECHA`,`ID`,`DNI`,`APELLIDO`,`NOMBRE`,`DIRECCION`,`TELEFONO`,`EMAIL`,`SEXO`,`FECHA_NACIMIENTO`,`FECHA_COBERTURA`,`SALDO`,`ID_TARIFA`,`ID_ZONA`,`ID_LOCALIDAD`,`ID_OBRA_SOCIAL`,`ID_ESTADO`,`ID_USUARIO_MODIFICA`,`ID_ENFERMEDAD`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.DNI, OLD.APELLIDO, OLD.NOMBRE, OLD.DIRECCION, OLD.TELEFONO, OLD.EMAIL, OLD.SEXO, OLD.FECHA_NACIMIENTO, OLD.FECHA_COBERTURA, OLD.SALDO, OLD.ID_TARIFA, OLD.ID_ZONA, OLD.ID_LOCALIDAD, OLD.ID_OBRA_SOCIAL, OLD.ID_ESTADO, OLD.ID_USUARIO_MODIFICA, OLD.ID_ENFERMEDAD, 'DELETE');
	END$$
DELIMITER ;