DELIMITER $$
	CREATE TRIGGER SOCIOS_BAJA_TRIGGER_UPDATE
	AFTER UPDATE ON SOCIOS_BAJA
	FOR EACH ROW
	BEGIN
	  INSERT INTO `SOCIOS_BAJA_AUDIT`(`FECHA`,`ID`,`ID_SOCIO`,`ID_MOTIVO_BAJA`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.ID_SOCIO, NEW.ID_MOTIVO_BAJA, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER SOCIOS_BAJA_TRIGGER_INSERT
	AFTER INSERT ON SOCIOS_BAJA
	FOR EACH ROW
	BEGIN
	  INSERT INTO `SOCIOS_BAJA_AUDIT`(`FECHA`,`ID`,`ID_SOCIO`,`ID_MOTIVO_BAJA`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.ID_SOCIO, NEW.ID_MOTIVO_BAJA, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER SOCIOS_BAJA_TRIGGER_DELETE
	AFTER DELETE ON SOCIOS_BAJA
	FOR EACH ROW
	BEGIN
	  INSERT INTO `SOCIOS_BAJA_AUDIT`(`FECHA`,`ID`,`ID_SOCIO`,`ID_MOTIVO_BAJA`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.ID_SOCIO, OLD.ID_MOTIVO_BAJA, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;