DELIMITER $$
	CREATE TRIGGER TARIFAS_TRIGGER_UPDATE
	AFTER UPDATE ON TARIFAS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `TARIFAS_AUDIT`(`FECHA`,`ID`,`NRO_TARIFA`,`DESCRIPCION`,`VALOR`,`ID_PLAN`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NRO_TARIFA, NEW.DESCRIPCION, NEW.VALOR, NEW.ID_PLAN, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER TARIFAS_TRIGGER_INSERT
	AFTER INSERT ON TARIFAS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `TARIFAS_AUDIT`(`FECHA`,`ID`,`NRO_TARIFA`,`DESCRIPCION`,`VALOR`,`ID_PLAN`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NRO_TARIFA, NEW.DESCRIPCION, NEW.VALOR, NEW.ID_PLAN, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER TARIFAS_TRIGGER_DELETE
	AFTER DELETE ON TARIFAS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `TARIFAS_AUDIT`(`FECHA`,`ID`,`NRO_TARIFA`,`DESCRIPCION`,`VALOR`,`ID_PLAN`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.NRO_TARIFA, OLD.DESCRIPCION, OLD.VALOR, OLD.ID_PLAN, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;