DELIMITER $$
	CREATE TRIGGER USUARIOS_TRIGGER_UPDATE
	AFTER UPDATE ON USUARIOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `USUARIOS_AUDIT`(`FECHA`,`ID`,`USERNAME`,`PASSWORD`,`ID_ROL`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.USERNAME, NEW.PASSWORD, NEW.ID_ROL, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER USUARIOS_TRIGGER_INSERT
	AFTER INSERT ON USUARIOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `USUARIOS_AUDIT`(`FECHA`,`ID`,`USERNAME`,`PASSWORD`,`ID_ROL`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.USERNAME, NEW.PASSWORD, NEW.ID_ROL, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER USUARIOS_TRIGGER_DELETE
	AFTER DELETE ON USUARIOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `USUARIOS_AUDIT`(`FECHA`,`ID`,`USERNAME`,`PASSWORD`,`ID_ROL`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.USERNAME, OLD.PASSWORD, OLD.ID_ROL, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;