DELIMITER $$
	CREATE TRIGGER ZONAS_TRIGGER_UPDATE
	AFTER UPDATE ON ZONAS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ZONAS_AUDIT`(`FECHA`,`ID`,`NRO_ZONA`,`NOMBRE`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NRO_ZONA, NEW.NOMBRE, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER ZONAS_TRIGGER_INSERT
	AFTER INSERT ON ZONAS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ZONAS_AUDIT`(`FECHA`,`ID`,`NRO_ZONA`,`NOMBRE`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NRO_ZONA, NEW.NOMBRE, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER ZONAS_TRIGGER_DELETE
	AFTER DELETE ON ZONAS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ZONAS_AUDIT`(`FECHA`,`ID`,`NRO_ZONA`,`NOMBRE`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.NRO_ZONA, OLD.NOMBRE, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;