DELIMITER $$
	CREATE TRIGGER ZONAS_COBRADORES_TRIGGER_UPDATE
	AFTER UPDATE ON ZONAS_COBRADORES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ZONAS_COBRADORES_AUDIT`(`FECHA`,`ID`,`ID_ZONA`,`ID_COBRADOR`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.ID_ZONA, NEW.ID_COBRADOR, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER ZONAS_COBRADORES_TRIGGER_INSERT
	AFTER INSERT ON ZONAS_COBRADORES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ZONAS_COBRADORES_AUDIT`(`FECHA`,`ID`,`ID_ZONA`,`ID_COBRADOR`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.ID_ZONA, NEW.ID_COBRADOR, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER ZONAS_COBRADORES_TRIGGER_DELETE
	AFTER DELETE ON ZONAS_COBRADORES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ZONAS_COBRADORES_AUDIT`(`FECHA`,`ID`,`ID_ZONA`,`ID_COBRADOR`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.ID_ZONA, OLD.ID_COBRADOR, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;