CREATE TABLE LOCALIDADES(
	ID INT(8) AUTO_INCREMENT,
	NRO_LOCALIDAD INT(8),
	NOMBRE VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE ZONAS(
	ID INT(8) AUTO_INCREMENT,
	NRO_ZONA INT(8),
	NOMBRE VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE COBRADORES(
	ID INT(8) AUTO_INCREMENT,
	DNI INT(8) NOT NULL UNIQUE KEY,
	APELLIDO VARCHAR(100) NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	DIRECCION VARCHAR(100) NOT NULL,
	TELEFONO VARCHAR(10) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	SEXO VARCHAR(10) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	FECHA_ALTA DATE NOT NULL,
	FECHA_BAJA DATE,
	ID_LOCALIDAD INT(8),
	PRIMARY KEY (ID),
	FOREIGN KEY (ID) REFERENCES LOCALIDADES(ID)
);

CREATE TABLE ZONAS_COBRADORES(
	ID INT(8) AUTO_INCREMENT,
	ID_ZONA INT(8),
	ID_COBRADOR INT(8),
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_ZONA) REFERENCES ZONAS(ID),
	FOREIGN KEY (ID_COBRADOR) REFERENCES COBRADORES(ID)
);

CREATE TABLE OBRAS_SOCIALES(
	ID INT(8) AUTO_INCREMENT,
	DESCRIPCION VARCHAR(50) NOT NULL, 
	FECHA_ALTA DATE NOT NULL,
	FECHA_BAJA DATE,
	USUARIO_ALTA INT(8),
	PRIMARY KEY (ID)
);

CREATE TABLE PLANES(
	ID INT(8) AUTO_INCREMENT,
	NRO_PLAN INT(8),
	DESCRIPCION VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE TARIFAS(
	ID INT(8) AUTO_INCREMENT,
	NRO_TARIFA INT(8),
	DESCRIPCION VARCHAR(50) NOT NULL,
	VALOR FLOAT NOT NULL, 
	ID_PLAN INT (8) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_PLAN) REFERENCES PLANES(ID)	
);

CREATE TABLE RANGOS_TARIFAS(
	ID INT(8) AUTO_INCREMENT,
	EDAD_DESDE INT(3) NOT NULL,
	EDAD_HASTA INT(3) NOT NULL,
	VALOR FLOAT NOT NULL, 
	ID_TARIFA INT(8) NOT NULL, 
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_TARIFA) REFERENCES TARIFAS(ID)
);

CREATE TABLE SOCIOS(
	ID INT(8) AUTO_INCREMENT,
	DNI INT(8) NOT NULL UNIQUE KEY,
	APELLIDO VARCHAR(100) NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	DIRECCION VARCHAR(100) NOT NULL,
	TELEFONO VARCHAR(10) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	SEXO VARCHAR(50) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	FECHA_COBERTURA DATE NOT NULL,
	USUARIO_ALTA INT(8) NOT NULL,
	SALDO FLOAT NOT NULL,
	ID_TARIFA INT(8) NOT NULL,
	ID_ZONA INT(8) NOT NULL,
	ID_LOCALIDAD INT(8) NOT NULL,
	ID_OBRA_SOCIAL INT(8) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_TARIFA) REFERENCES TARIFAS(ID),
	FOREIGN KEY (ID_ZONA) REFERENCES ZONAS(ID),
	FOREIGN KEY (ID_LOCALIDAD) REFERENCES LOCALIDADES(ID),
	FOREIGN KEY (ID_OBRA_SOCIAL) REFERENCES OBRAS_SOCIALES(ID)
);

CREATE TABLE ADHERENTES(
	ID INT(8) AUTO_INCREMENT,
	DNI INT(8) NOT NULL UNIQUE KEY,
	APELLIDO VARCHAR(100) NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	DIRECCION VARCHAR(100) NOT NULL,
	TELEFONO VARCHAR(10) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	SEXO VARCHAR(50) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	FECHA_COBERTURA DATE NOT NULL,
	USUARIO_ALTA INT(8) NOT NULL,
	SALDO FLOAT NOT NULL,
	ID_SOCIO INT(8) NOT NULL,
	ID_ZONA INT(8) NOT NULL,
	ID_LOCALIDAD INT(8) NOT NULL,
	ID_OBRA_SOCIAL INT(8) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_SOCIO) REFERENCES SOCIOS(ID),
	FOREIGN KEY (ID_LOCALIDAD) REFERENCES LOCALIDADES(ID),
	FOREIGN KEY (ID_OBRA_SOCIAL) REFERENCES OBRAS_SOCIALES(ID)
);

CREATE TABLE ESTADOS(
	ID INT(8) AUTO_INCREMENT,
	NRO_ESTADO INT(8),
	DESCRIPCION VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE HISTORIAL_ESTADO_SOCIOS(
	ID INT(8) AUTO_INCREMENT,
	FECHA_ALTA DATE NOT NULL DEFAULT CURRENT_DATE,
	MOTIVO_BAJA VARCHAR(50),
	ID_SOCIO INT(8) NOT NULL,
	ID_ESTADO INT(8) NOT NULL, 
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_SOCIO) REFERENCES SOCIOS(ID),
	FOREIGN KEY (ID_ESTADO) REFERENCES ESTADOS(ID)
);

CREATE TABLE HISTORIAL_ESTADO_ADHERENTES(
	ID INT(8) AUTO_INCREMENT,
	FECHA_ALTA DATE NOT NULL DEFAULT CURRENT_DATE,
	MOTIVO_BAJA VARCHAR(50),
	ID_ADHERENTE INT(8) NOT NULL,
	ID_ESTADO INT(8) NOT NULL, 
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_ADHERENTE) REFERENCES ADHERENTES(ID),
	FOREIGN KEY (ID_ESTADO) REFERENCES ESTADOS(ID)
);

CREATE TABLE PARAMETROS_EMPRESA(
	ID INT(8) AUTO_INCREMENT,
	NOMBRE VARCHAR(100) NOT NULL,
	DIRECCION VARCHAR(100) NOT NULL,
	CUIT INT(11) NOT NULL,
	INICIO_ACTIVIDADES DATE NOT NULL,
	CONDICION_IVA VARCHAR(25) NOT NULL,
	CONDICION_IIBB VARCHAR(25) NOT NULL,
	TELEFONO VARCHAR(10) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	ID_LOCALIDAD INT(8) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_LOCALIDAD) REFERENCES LOCALIDADES(ID)
);

CREATE TABLE COMPROBANTES(
	ID INT(8) AUTO_INCREMENT,
	NRO_COMPROBANTE INT(8) NOT NULL,
	FECHA_ALTA DATE NOT NULL DEFAULT CURRENT_DATE,
	ID_PARAMETRO INT(8) NOT NULL, 
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_PARAMETRO) REFERENCES PARAMETROS_EMPRESA(ID)
);

CREATE TABLE PAGOS(
	ID INT(8) AUTO_INCREMENT,
	VALOR FLOAT NOT NULL,
	FECHA_ALTA DATE NOT NULL DEFAULT CURRENT_DATE,
	ID_SOCIO INT(8) NOT NULL,
	ID_COBRADOR INT(8) NOT NULL,
	ID_COMPROBANTE INT(8) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_SOCIO) REFERENCES SOCIOS(ID),
	FOREIGN KEY (ID_COBRADOR) REFERENCES COBRADORES(ID),
	FOREIGN KEY (ID_COMPROBANTE) REFERENCES COMPROBANTES(ID)
);