DROP TABLE IF EXISTS `usuarios`;

CREATE TABLE `usuarios` (
  `ID` int(8) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(20) NOT NULL,
  `PASSWORD` varchar(50) DEFAULT NULL,
  `ID_ROL` int(8) NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USERNAME` (`USERNAME`),
  KEY `ID_ROL` (`ID_ROL`),
  KEY `ID_USUARIO_MODIFICA` (`ID_USUARIO_MODIFICA`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

insert  into `usuarios`(`ID`,`USERNAME`,`PASSWORD`,`ID_ROL`,`ID_USUARIO_MODIFICA`) values 
(1,'fausto','fedele',1,1),
(2,'nacho','cabrera',1,1);

DROP TABLE IF EXISTS `usuarios_audit`;

CREATE TABLE `usuarios_audit` (
  `ID_AUDIT` int(8) NOT NULL AUTO_INCREMENT,
  `FECHA` datetime NOT NULL,
  `METODO` varchar(6) NOT NULL,
  `ID` int(8) NOT NULL,
  `USERNAME` varchar(20) NOT NULL,
  `PASSWORD` varchar(50) DEFAULT NULL,
  `ID_ROL` int(8) NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID_AUDIT`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `motivos_baja`;

CREATE TABLE `motivos_baja` (
  `ID` int(8) NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` varchar(100) DEFAULT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ID_USUARIO_MODIFICA` (`ID_USUARIO_MODIFICA`),
  CONSTRAINT `MOTIVOS_BAJA_ibfk_1` FOREIGN KEY (`ID_USUARIO_MODIFICA`) REFERENCES `usuarios` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

insert  into `motivos_baja`(`ID`,`DESCRIPCION`,`ID_USUARIO_MODIFICA`) values 
(1,'MOROSIDAD',1),
(2,'FALLECIMIENTO',1),
(3,'RENUNCIA',1);

DROP TABLE IF EXISTS `motivos_baja_audit`;

CREATE TABLE `motivos_baja_audit` (
  `ID_AUDIT` int(8) NOT NULL AUTO_INCREMENT,
  `FECHA` datetime NOT NULL,
  `METODO` varchar(6) NOT NULL,
  `ID` int(8) NOT NULL,
  `DESCRIPCION` varchar(100) DEFAULT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID_AUDIT`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `provincias`;

CREATE TABLE `provincias` (
  `ID` int(8) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(50) NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ID_USUARIO_MODIFICA` (`ID_USUARIO_MODIFICA`),
  CONSTRAINT `PROVINCIAS_ibfk_1` FOREIGN KEY (`ID_USUARIO_MODIFICA`) REFERENCES `usuarios` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=latin1;

insert  into `provincias`(`ID`,`NOMBRE`,`ID_USUARIO_MODIFICA`) values 
(1,'BUENOS AIRES',1),
(2,'CAPITAL FEDERAL',1),
(3,'CATAMARCA',1),
(4,'CHACO',1),
(5,'CHUBUT',1),
(6,'CÓRDOBA',1),
(7,'CORRIENTES',1),
(8,'ENTRE RÍOS',1),
(9,'FORMOSA',1),
(10,'JUJUY',1),
(11,'LA PAMPA',1),
(12,'LA RIOJA',1),
(13,'MENDOZA',1),
(14,'MISIONES',1),
(15,'NEUQUÉN',1),
(16,'RÍO NEGRO',1),
(17,'SALTA',1),
(18,'SAN JUAN',1),
(19,'SAN LUIS',1),
(20,'SANTA CRUZ',1),
(21,'SANTA FE',1),
(22,'SANTIAGO DEL ESTERO',1),
(23,'TIERRA DEL FUEGO',1),
(24,'TUCUMÁN',1);

DROP TABLE IF EXISTS `provincias_audit`;

CREATE TABLE `provincias_audit` (
  `ID_AUDIT` int(8) NOT NULL AUTO_INCREMENT,
  `FECHA` datetime NOT NULL,
  `METODO` varchar(6) NOT NULL,
  `ID` int(8) NOT NULL,
  `NOMBRE` varchar(50) NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID_AUDIT`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `localidades`;

CREATE TABLE `localidades` (
  `ID` int(8) NOT NULL AUTO_INCREMENT,
  `NRO_LOCALIDAD` int(8) DEFAULT NULL,
  `NOMBRE` varchar(60) DEFAULT NULL,
  `CODIGO_POSTAL` int(4) NOT NULL,
  `ID_PROVINCIA` int(8) NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ID_PROVINCIA` (`ID_PROVINCIA`),
  KEY `ID_USUARIO_MODIFICA` (`ID_USUARIO_MODIFICA`),
  CONSTRAINT `LOCALIDADES_ibfk_1` FOREIGN KEY (`ID_PROVINCIA`) REFERENCES `provincias` (`ID`),
  CONSTRAINT `LOCALIDADES_ibfk_2` FOREIGN KEY (`ID_USUARIO_MODIFICA`) REFERENCES `usuarios` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

insert  into `localidades`(`ID`,`NRO_LOCALIDAD`,`NOMBRE`,`CODIGO_POSTAL`,`ID_PROVINCIA`,`ID_USUARIO_MODIFICA`) values 
(NULL,1,'BOVRIL',3142,8,1),
(NULL,2,'ALCARAZ',3138,8,1),
(NULL,3,'SAUCE DE LUNA',3144,8,1),
(NULL,4,'COLONIA AVIGDOR',3142,8,1),
(NULL,5,'PARANA',3100,8,1),
(NULL,6,'CONSCRIPTO BERNARDI',3188,8,1),
(NULL,7,'FEDERAL',3180,8,1);

DROP TABLE IF EXISTS `localidades_audit`;

CREATE TABLE `localidades_audit` (
  `ID_AUDIT` int(8) NOT NULL AUTO_INCREMENT,
  `FECHA` datetime NOT NULL,
  `METODO` varchar(6) NOT NULL,
  `ID` int(8) NOT NULL,
  `NRO_LOCALIDAD` int(8) DEFAULT NULL,
  `NOMBRE` varchar(60) DEFAULT NULL,
  `CODIGO_POSTAL` int(4) NOT NULL,
  `ID_PROVINCIA` int(8) NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID_AUDIT`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `planes`;

CREATE TABLE `planes` (
  `ID` int(8) NOT NULL AUTO_INCREMENT,
  `NRO_PLAN` int(8) DEFAULT NULL,
  `DESCRIPCION` varchar(50) NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ID_USUARIO_MODIFICA` (`ID_USUARIO_MODIFICA`),
  CONSTRAINT `PLANES_ibfk_1` FOREIGN KEY (`ID_USUARIO_MODIFICA`) REFERENCES `usuarios` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

insert  into `planes`(`ID`,`NRO_PLAN`,`DESCRIPCION`,`ID_USUARIO_MODIFICA`) values 
(1,1,'INDIVIDUAL',1),
(2,2,'TITULAR Y ADHERENTE',1),
(3,3,'FAMILIAR',1);

DROP TABLE IF EXISTS `planes_audit`;

CREATE TABLE `planes_audit` (
  `ID_AUDIT` int(8) NOT NULL AUTO_INCREMENT,
  `FECHA` datetime NOT NULL,
  `METODO` varchar(6) NOT NULL,
  `ID` int(8) NOT NULL,
  `NRO_PLAN` int(8) DEFAULT NULL,
  `DESCRIPCION` varchar(50) NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID_AUDIT`),
  KEY `ID_USUARIO_MODIFICA` (`ID_USUARIO_MODIFICA`),
  CONSTRAINT `PLANES_AUDIT_ibfk_1` FOREIGN KEY (`ID_USUARIO_MODIFICA`) REFERENCES `usuarios` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `tarifas`;

CREATE TABLE `tarifas` (
  `ID` int(8) NOT NULL AUTO_INCREMENT,
  `NRO_TARIFA` int(8) DEFAULT NULL,
  `DESCRIPCION` varchar(50) NOT NULL,
  `VALOR` decimal(10,2) DEFAULT NULL,
  `ID_PLAN` int(8) NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ID_PLAN` (`ID_PLAN`),
  KEY `ID_USUARIO_MODIFICA` (`ID_USUARIO_MODIFICA`),
  CONSTRAINT `TARIFAS_ibfk_1` FOREIGN KEY (`ID_PLAN`) REFERENCES `planes` (`ID`),
  CONSTRAINT `TARIFAS_ibfk_2` FOREIGN KEY (`ID_USUARIO_MODIFICA`) REFERENCES `usuarios` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `tarifas_audit`;

CREATE TABLE `tarifas_audit` (
  `ID_AUDIT` int(8) NOT NULL AUTO_INCREMENT,
  `FECHA` datetime NOT NULL,
  `METODO` varchar(6) NOT NULL,
  `ID` int(8) NOT NULL,
  `NRO_TARIFA` int(8) DEFAULT NULL,
  `DESCRIPCION` varchar(50) NOT NULL,
  `VALOR` float NOT NULL,
  `ID_PLAN` int(8) NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID_AUDIT`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `zonas`;

CREATE TABLE `zonas` (
  `ID` int(8) NOT NULL AUTO_INCREMENT,
  `NRO_ZONA` int(8) DEFAULT NULL,
  `NOMBRE` varchar(50) NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ID_USUARIO_MODIFICA` (`ID_USUARIO_MODIFICA`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `zonas_audit`;

CREATE TABLE `zonas_audit` (
  `ID_AUDIT` int(8) NOT NULL AUTO_INCREMENT,
  `FECHA` datetime NOT NULL,
  `METODO` varchar(6) NOT NULL,
  `ID` int(8) NOT NULL,
  `NRO_ZONA` int(8) DEFAULT NULL,
  `NOMBRE` varchar(50) NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID_AUDIT`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `obras_sociales`;

CREATE TABLE `obras_sociales` (
  `ID` int(8) NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` varchar(50) NOT NULL,
  `TIENE_SEPELIO` tinyint(1) NOT NULL DEFAULT 0,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ID_USUARIO_MODIFICA` (`ID_USUARIO_MODIFICA`),
  CONSTRAINT `OBRAS_SOCIALES_ibfk_1` FOREIGN KEY (`ID_USUARIO_MODIFICA`) REFERENCES `usuarios` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `obras_sociales_audit`;

CREATE TABLE `obras_sociales_audit` (
  `ID_AUDIT` int(8) NOT NULL AUTO_INCREMENT,
  `FECHA` datetime NOT NULL,
  `METODO` varchar(6) NOT NULL,
  `ID` int(8) NOT NULL,
  `DESCRIPCION` varchar(50) NOT NULL,
  `TIENE_SEPELIO` tinyint(1) NOT NULL DEFAULT 0,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID_AUDIT`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `estados`;

CREATE TABLE `estados` (
  `ID` int(8) NOT NULL AUTO_INCREMENT,
  `NRO_ESTADO` int(8) DEFAULT NULL,
  `DESCRIPCION` varchar(50) NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ID_USUARIO_MODIFICA` (`ID_USUARIO_MODIFICA`),
  CONSTRAINT `ESTADOS_ibfk_1` FOREIGN KEY (`ID_USUARIO_MODIFICA`) REFERENCES `usuarios` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

insert  into `estados`(`ID`,`NRO_ESTADO`,`DESCRIPCION`,`ID_USUARIO_MODIFICA`) values 
(1,1,'ALTA',1),
(2,2,'BAJA',1);

DROP TABLE IF EXISTS `estados_audit`;

CREATE TABLE `estados_audit` (
  `ID_AUDIT` int(8) NOT NULL AUTO_INCREMENT,
  `FECHA` datetime NOT NULL,
  `METODO` varchar(6) NOT NULL,
  `ID` int(8) NOT NULL,
  `NRO_ESTADO` int(8) DEFAULT NULL,
  `DESCRIPCION` varchar(50) NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID_AUDIT`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `enfermedades`;

CREATE TABLE `enfermedades` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4;

insert  into `enfermedades`(`ID`,`DESCRIPCION`) values 
(1,'SIN ENFERMEDAD'),
(2,'SISTEMA URINARIO'),
(3,'DIABETES'),
(4,'INFECCIOSAS Y PARASITARIAS'),
(5,'SISTEMA RESPIRATORIO'),
(6,'TUMORES'),
(7,'SISTEMA CIRCULATORIO');

DROP TABLE IF EXISTS `enfermedades_audit`;

CREATE TABLE `enfermedades_audit` (
  `ID_AUDIT` int NOT NULL AUTO_INCREMENT,
  `FECHA` datetime NOT NULL,
  `ID` int NOT NULL,
  `DESCRIPCION` varchar(100) NOT NULL,
  `METODO` varchar(6) NOT NULL,
  PRIMARY KEY (`ID_AUDIT`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `socios`;

CREATE TABLE `socios` (
  `ID` int(8) NOT NULL AUTO_INCREMENT,
  `DNI` int(8) NOT NULL,
  `APELLIDO` varchar(100) NOT NULL,
  `NOMBRE` varchar(100) NOT NULL,
  `DIRECCION` varchar(100) NOT NULL,
  `TELEFONO` varchar(10) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `SEXO` varchar(50) NOT NULL,
  `FECHA_NACIMIENTO` date NOT NULL,
  `FECHA_COBERTURA` date NOT NULL,
  `SALDO` float NOT NULL,
  `ID_TARIFA` int(8) NOT NULL,
  `ID_ZONA` int(8) NOT NULL,
  `ID_LOCALIDAD` int(8) NOT NULL,
  `ID_OBRA_SOCIAL` int(8) NOT NULL,
  `ID_ESTADO` int(8) NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  `ID_ENFERMEDAD` int(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `DNI` (`DNI`),
  KEY `ID_TARIFA` (`ID_TARIFA`),
  KEY `ID_ZONA` (`ID_ZONA`),
  KEY `ID_LOCALIDAD` (`ID_LOCALIDAD`),
  KEY `ID_OBRA_SOCIAL` (`ID_OBRA_SOCIAL`),
  KEY `ID_ESTADO` (`ID_ESTADO`),
  KEY `ID_USUARIO_MODIFICA` (`ID_USUARIO_MODIFICA`),
  KEY `SOCIOS_ibfk_7` (`ID_ENFERMEDAD`),
  CONSTRAINT `SOCIOS_ibfk_1` FOREIGN KEY (`ID_TARIFA`) REFERENCES `tarifas` (`ID`),
  CONSTRAINT `SOCIOS_ibfk_2` FOREIGN KEY (`ID_ZONA`) REFERENCES `zonas` (`ID`),
  CONSTRAINT `SOCIOS_ibfk_3` FOREIGN KEY (`ID_LOCALIDAD`) REFERENCES `localidades` (`ID`),
  CONSTRAINT `SOCIOS_ibfk_4` FOREIGN KEY (`ID_OBRA_SOCIAL`) REFERENCES `obras_sociales` (`ID`),
  CONSTRAINT `SOCIOS_ibfk_5` FOREIGN KEY (`ID_ESTADO`) REFERENCES `estados` (`ID`),
  CONSTRAINT `SOCIOS_ibfk_6` FOREIGN KEY (`ID_USUARIO_MODIFICA`) REFERENCES `usuarios` (`ID`),
  CONSTRAINT `SOCIOS_ibfk_7` FOREIGN KEY (`ID_ENFERMEDAD`) REFERENCES `enfermedades` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `socios_audit`;

CREATE TABLE `socios_audit` (
  `ID_AUDIT` int(8) NOT NULL AUTO_INCREMENT,
  `FECHA` datetime NOT NULL,
  `METODO` varchar(6) NOT NULL,
  `ID` int(8) NOT NULL,
  `DNI` int(8) NOT NULL,
  `APELLIDO` varchar(100) NOT NULL,
  `NOMBRE` varchar(100) NOT NULL,
  `DIRECCION` varchar(100) NOT NULL,
  `TELEFONO` varchar(10) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `SEXO` varchar(50) NOT NULL,
  `FECHA_NACIMIENTO` date NOT NULL,
  `FECHA_COBERTURA` date NOT NULL,
  `SALDO` float NOT NULL,
  `ID_TARIFA` int(8) NOT NULL,
  `ID_ZONA` int(8) NOT NULL,
  `ID_LOCALIDAD` int(8) NOT NULL,
  `ID_OBRA_SOCIAL` int(8) NOT NULL,
  `ID_ESTADO` int(8) NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  `ID_ENFERMEDAD` int(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID_AUDIT`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `socios_baja`;

CREATE TABLE `socios_baja` (
  `ID` int(8) NOT NULL AUTO_INCREMENT,
  `ID_SOCIO` int(8) DEFAULT NULL,
  `ID_MOTIVO_BAJA` int(8) DEFAULT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ID_MOTIVO_BAJA` (`ID_MOTIVO_BAJA`),
  KEY `ID_SOCIO` (`ID_SOCIO`),
  KEY `ID_USUARIO_MODIFICA` (`ID_USUARIO_MODIFICA`),
  CONSTRAINT `SOCIOS_BAJA_ibfk_1` FOREIGN KEY (`ID_MOTIVO_BAJA`) REFERENCES `motivos_baja` (`ID`),
  CONSTRAINT `SOCIOS_BAJA_ibfk_2` FOREIGN KEY (`ID_SOCIO`) REFERENCES `socios` (`ID`),
  CONSTRAINT `SOCIOS_BAJA_ibfk_3` FOREIGN KEY (`ID_USUARIO_MODIFICA`) REFERENCES `usuarios` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `socios_baja_audit`;

CREATE TABLE `socios_baja_audit` (
  `ID_AUDIT` int(11) NOT NULL AUTO_INCREMENT,
  `FECHA` datetime NOT NULL,
  `ID` int(11) NOT NULL,
  `ID_SOCIO` int(11) DEFAULT NULL,
  `ID_MOTIVO_BAJA` int(11) DEFAULT NULL,
  `ID_USUARIO_MODIFICA` int(11) NOT NULL,
  `METODO` varchar(6) NOT NULL,
  PRIMARY KEY (`ID_AUDIT`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `roles`;

CREATE TABLE `roles` (
  `ID` int(8) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(10) NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NOMBRE` (`NOMBRE`),
  KEY `ID_USUARIO_MODIFICA` (`ID_USUARIO_MODIFICA`),
  CONSTRAINT `ROLES_ibfk_1` FOREIGN KEY (`ID_USUARIO_MODIFICA`) REFERENCES `usuarios` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

insert  into `roles`(`ID`,`NOMBRE`,`ID_USUARIO_MODIFICA`) values 
(1,'ADMIN',1);

DROP TABLE IF EXISTS `roles_audit`;

DROP TABLE IF EXISTS `rangos_tarifas`;

CREATE TABLE `rangos_tarifas` (
  `ID` int(8) NOT NULL AUTO_INCREMENT,
  `EDAD_DESDE` int(3) NOT NULL,
  `EDAD_HASTA` int(3) NOT NULL,
  `VALOR` decimal(10,2) NOT NULL,
  `ID_TARIFA` int(8) NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ID_USUARIO_MODIFICA` (`ID_USUARIO_MODIFICA`),
  KEY `RANGOS_TARIFAS_ibfk_1` (`ID_TARIFA`),
  CONSTRAINT `RANGOS_TARIFAS_ibfk_1` FOREIGN KEY (`ID_TARIFA`) REFERENCES `tarifas` (`ID`),
  CONSTRAINT `RANGOS_TARIFAS_ibfk_2` FOREIGN KEY (`ID_USUARIO_MODIFICA`) REFERENCES `usuarios` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=559 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `rangos_tarifas_audit`;

CREATE TABLE `rangos_tarifas_audit` (
  `ID_AUDIT` int(8) NOT NULL AUTO_INCREMENT,
  `FECHA` datetime NOT NULL,
  `METODO` varchar(6) NOT NULL,
  `ID` int(8) NOT NULL,
  `EDAD_DESDE` int(3) NOT NULL,
  `EDAD_HASTA` int(3) NOT NULL,
  `VALOR` float NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  `ID_TARIFA` int(8) NOT NULL,
  PRIMARY KEY (`ID_AUDIT`)
) ENGINE=InnoDB AUTO_INCREMENT=174 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `parametros_empresa`;

CREATE TABLE `parametros_empresa` (
  `ID` int(8) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(100) NOT NULL,
  `DIRECCION` varchar(100) NOT NULL,
  `CUIT` bigint(20) NOT NULL,
  `INICIO_ACTIVIDADES` date NOT NULL,
  `CONDICION_IVA` varchar(25) NOT NULL,
  `CONDICION_IIBB` varchar(25) NOT NULL,
  `TELEFONO` varchar(10) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `ID_LOCALIDAD` int(8) NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ID_LOCALIDAD` (`ID_LOCALIDAD`),
  KEY `ID_USUARIO_MODIFICA` (`ID_USUARIO_MODIFICA`),
  CONSTRAINT `PARAMETROS_EMPRESA_ibfk_1` FOREIGN KEY (`ID_LOCALIDAD`) REFERENCES `localidades` (`ID`),
  CONSTRAINT `PARAMETROS_EMPRESA_ibfk_2` FOREIGN KEY (`ID_USUARIO_MODIFICA`) REFERENCES `usuarios` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

insert  into `parametros_empresa`(`ID`,`NOMBRE`,`DIRECCION`,`CUIT`,`INICIO_ACTIVIDADES`,`CONDICION_IVA`,`CONDICION_IIBB`,`TELEFONO`,`EMAIL`,`ID_LOCALIDAD`,`ID_USUARIO_MODIFICA`) values 
(1,'COCHERIA ZURDO','ALTE. BROWN 153',20390322543,'1995-09-01','EXENTO','EXENTO','3438407340','info@cocheriazurdo.com',1,1);

DROP TABLE IF EXISTS `parametros_empresa_audit`;

CREATE TABLE `parametros_empresa_audit` (
  `ID_AUDIT` int(8) NOT NULL AUTO_INCREMENT,
  `FECHA` datetime NOT NULL,
  `METODO` varchar(6) NOT NULL,
  `ID` int(8) NOT NULL,
  `NOMBRE` varchar(100) NOT NULL,
  `DIRECCION` varchar(100) NOT NULL,
  `CUIT` int(11) NOT NULL,
  `INICIO_ACTIVIDADES` date NOT NULL,
  `CONDICION_IVA` varchar(25) NOT NULL,
  `CONDICION_IIBB` varchar(25) NOT NULL,
  `TELEFONO` varchar(10) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `ID_LOCALIDAD` int(8) NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID_AUDIT`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `cobradores`;

CREATE TABLE `cobradores` (
  `ID` int(8) NOT NULL AUTO_INCREMENT,
  `DNI` int(8) NOT NULL,
  `APELLIDO` varchar(100) NOT NULL,
  `NOMBRE` varchar(100) NOT NULL,
  `DIRECCION` varchar(100) NOT NULL,
  `TELEFONO` varchar(10) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `SEXO` varchar(10) NOT NULL,
  `FECHA_NACIMIENTO` date NOT NULL,
  `ID_LOCALIDAD` int(8) DEFAULT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `DNI` (`DNI`),
  KEY `ID_LOCALIDAD` (`ID_LOCALIDAD`),
  KEY `ID_USUARIO_MODIFICA` (`ID_USUARIO_MODIFICA`),
  CONSTRAINT `COBRADORES_ibfk_1` FOREIGN KEY (`ID_LOCALIDAD`) REFERENCES `localidades` (`ID`),
  CONSTRAINT `COBRADORES_ibfk_2` FOREIGN KEY (`ID_USUARIO_MODIFICA`) REFERENCES `usuarios` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `cobradores_audit`;

CREATE TABLE `cobradores_audit` (
  `ID_AUDIT` int(8) NOT NULL AUTO_INCREMENT,
  `FECHA` datetime NOT NULL,
  `METODO` varchar(6) NOT NULL,
  `ID` int(8) NOT NULL,
  `DNI` int(8) NOT NULL,
  `APELLIDO` varchar(100) NOT NULL,
  `NOMBRE` varchar(100) NOT NULL,
  `DIRECCION` varchar(100) NOT NULL,
  `TELEFONO` varchar(10) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `SEXO` varchar(10) NOT NULL,
  `FECHA_NACIMIENTO` date NOT NULL,
  `ID_LOCALIDAD` int(8) DEFAULT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID_AUDIT`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `adherentes`;

CREATE TABLE `adherentes` (
  `ID` int(8) NOT NULL AUTO_INCREMENT,
  `DNI` int(8) NOT NULL,
  `APELLIDO` varchar(100) NOT NULL,
  `NOMBRE` varchar(100) NOT NULL,
  `DIRECCION` varchar(100) NOT NULL,
  `TELEFONO` varchar(10) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `SEXO` varchar(50) NOT NULL,
  `FECHA_NACIMIENTO` date NOT NULL,
  `FECHA_COBERTURA` date NOT NULL,
  `SALDO` float NOT NULL,
  `ID_SOCIO` int(8) NOT NULL,
  `ID_ZONA` int(8) NOT NULL,
  `ID_LOCALIDAD` int(8) NOT NULL,
  `ID_OBRA_SOCIAL` int(8) NOT NULL,
  `ID_ESTADO` int(8) NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  `ID_ENFERMEDAD` int(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `DNI` (`DNI`),
  KEY `ID_SOCIO` (`ID_SOCIO`),
  KEY `ID_LOCALIDAD` (`ID_LOCALIDAD`),
  KEY `ID_OBRA_SOCIAL` (`ID_OBRA_SOCIAL`),
  KEY `ID_ZONA` (`ID_ZONA`),
  KEY `ID_ESTADO` (`ID_ESTADO`),
  KEY `ID_USUARIO_MODIFICA` (`ID_USUARIO_MODIFICA`),
  KEY `ADHERENTES_ibfk_7` (`ID_ENFERMEDAD`),
  CONSTRAINT `ADHERENTES_ibfk_1` FOREIGN KEY (`ID_SOCIO`) REFERENCES `socios` (`ID`),
  CONSTRAINT `ADHERENTES_ibfk_2` FOREIGN KEY (`ID_LOCALIDAD`) REFERENCES `localidades` (`ID`),
  CONSTRAINT `ADHERENTES_ibfk_3` FOREIGN KEY (`ID_OBRA_SOCIAL`) REFERENCES `obras_sociales` (`ID`),
  CONSTRAINT `ADHERENTES_ibfk_4` FOREIGN KEY (`ID_ZONA`) REFERENCES `zonas` (`ID`),
  CONSTRAINT `ADHERENTES_ibfk_5` FOREIGN KEY (`ID_ESTADO`) REFERENCES `estados` (`ID`),
  CONSTRAINT `ADHERENTES_ibfk_6` FOREIGN KEY (`ID_USUARIO_MODIFICA`) REFERENCES `usuarios` (`ID`),
  CONSTRAINT `ADHERENTES_ibfk_7` FOREIGN KEY (`ID_ENFERMEDAD`) REFERENCES `enfermedades` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `adherentes_audit`;

CREATE TABLE `adherentes_audit` (
  `ID_AUDIT` int(8) NOT NULL AUTO_INCREMENT,
  `FECHA` datetime NOT NULL,
  `ID` int(8) NOT NULL,
  `DNI` int(8) NOT NULL,
  `APELLIDO` varchar(100) NOT NULL,
  `NOMBRE` varchar(100) NOT NULL,
  `DIRECCION` varchar(100) NOT NULL,
  `TELEFONO` varchar(10) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `SEXO` varchar(50) NOT NULL,
  `FECHA_NACIMIENTO` date NOT NULL,
  `FECHA_COBERTURA` date NOT NULL,
  `SALDO` float NOT NULL,
  `ID_SOCIO` int(8) NOT NULL,
  `ID_ZONA` int(8) NOT NULL,
  `ID_LOCALIDAD` int(8) NOT NULL,
  `ID_OBRA_SOCIAL` int(8) NOT NULL,
  `ID_ESTADO` int(8) NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  `METODO` varchar(6) NOT NULL,
  `ID_ENFERMEDAD` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_AUDIT`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `adherentes_baja`;

CREATE TABLE `adherentes_baja` (
  `ID` int(8) NOT NULL AUTO_INCREMENT,
  `ID_ADHERENTE` int(8) DEFAULT NULL,
  `ID_MOTIVO_BAJA` int(8) DEFAULT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ID_MOTIVO_BAJA` (`ID_MOTIVO_BAJA`),
  KEY `ID_ADHERENTE` (`ID_ADHERENTE`),
  KEY `ID_USUARIO_MODIFICA` (`ID_USUARIO_MODIFICA`),
  CONSTRAINT `ADHERENTES_BAJA_ibfk_1` FOREIGN KEY (`ID_MOTIVO_BAJA`) REFERENCES `motivos_baja` (`ID`),
  CONSTRAINT `ADHERENTES_BAJA_ibfk_2` FOREIGN KEY (`ID_ADHERENTE`) REFERENCES `adherentes` (`ID`),
  CONSTRAINT `ADHERENTES_BAJA_ibfk_3` FOREIGN KEY (`ID_USUARIO_MODIFICA`) REFERENCES `usuarios` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

CREATE TABLE `adherentes_baja_audit` (
  `ID_AUDIT` int(8) NOT NULL AUTO_INCREMENT,
  `FECHA` datetime NOT NULL,
  `METODO` varchar(6) NOT NULL,
  `ID` int(8) NOT NULL,
  `ID_ADHERENTE` int(8) DEFAULT NULL,
  `ID_MOTIVO_BAJA` int(8) DEFAULT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID_AUDIT`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `cobertura_edades`;

CREATE TABLE `cobertura_edades` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `EDAD_DESDE` int(11) NOT NULL,
  `EDAD_HASTA` int(11) NOT NULL,
  `INDICADOR` float(6,4) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4;

insert  into `cobertura_edades`(`ID`,`EDAD_DESDE`,`EDAD_HASTA`,`INDICADOR`) values 
(1,0,0,7.1287),
(2,1,4,0.4707),
(3,5,14,0.0000),
(4,5,14,0.0000),
(5,15,24,0.0000),
(6,25,34,0.0000),
(7,35,44,0.2382),
(8,45,54,0.8970),
(9,55,64,2.7805),
(10,65,74,7.4754),
(11,75,120,17.7609);

DROP TABLE IF EXISTS `cobertura_edades_audit`;

CREATE TABLE `cobertura_edades_audit` (
  `ID_AUDIT` int NOT NULL AUTO_INCREMENT,
  `FECHA` datetime NOT NULL,
  `ID` int NOT NULL,
  `EDAD_DESDE` int NOT NULL,
  `EDAD_HASTA` int NOT NULL,
  `INDICADOR` float(6,4) NOT NULL,
  `METODO` varchar(6) NOT NULL,
  PRIMARY KEY (`ID_AUDIT`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `cobertura_enfermedades`;

CREATE TABLE `cobertura_enfermedades` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_ENFERMEDAD` int(11) NOT NULL,
  `INDICADOR` float(6,4) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ID_ENFERMEDAD` (`ID_ENFERMEDAD`),
  CONSTRAINT `cobertura_enfermedades_ibfk_1` FOREIGN KEY (`ID_ENFERMEDAD`) REFERENCES `enfermedades` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4;

insert  into `cobertura_enfermedades`(`ID`,`ID_ENFERMEDAD`,`INDICADOR`) values 
(1,1,1.0000),
(2,2,4.8688),
(3,3,4.8688),
(4,4,4.9628),
(5,5,7.3438),
(6,6,9.4809),
(7,7,13.0592);

DROP TABLE IF EXISTS `cobertura_enfermedades_audit`;

CREATE TABLE `cobertura_enfermedades_audit` (
  `ID_AUDIT` int NOT NULL AUTO_INCREMENT,
  `FECHA` datetime NOT NULL,
  `ID` int NOT NULL,
  `ID_ENFERMEDAD` int NOT NULL,
  `INDICADOR` float(6,4) NOT NULL,
  `METODO` varchar(6) NOT NULL,
  PRIMARY KEY (`ID_AUDIT`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `cobertura_pesos`;

CREATE TABLE `cobertura_pesos` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` varchar(50) NOT NULL,
  `PESO` float(3,2) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

insert  into `cobertura_pesos`(`ID`,`DESCRIPCION`,`PESO`) values 
(1,'ENFERMEDAD',1.25),
(2,'EDAD',1.50);

DROP TABLE IF EXISTS `cobertura_pesos_audit`;

CREATE TABLE `cobertura_pesos_audit` (
  `ID_AUDIT` int NOT NULL AUTO_INCREMENT,
  `FECHA` datetime NOT NULL,
  `ID` int NOT NULL,
  `DESCRIPCION` varchar(50) NOT NULL,
  `PESO` float(3,2) NOT NULL,
  `METODO` varchar(6) NOT NULL,
  PRIMARY KEY (`ID_AUDIT`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `comprobantes`;

CREATE TABLE `comprobantes` (
  `ID` int(8) NOT NULL AUTO_INCREMENT,
  `NRO_COMPROBANTE` bigint(20) NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  `IMPORTE_TOTAL` double NOT NULL DEFAULT 0,
  `ID_SOCIO` int(8) NOT NULL,
  `impreso` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `ID_USUARIO_MODIFICA` (`ID_USUARIO_MODIFICA`),
  KEY `ID_SOCIO` (`ID_SOCIO`),
  CONSTRAINT `COMPROBANTES_ibfk_2` FOREIGN KEY (`ID_USUARIO_MODIFICA`) REFERENCES `usuarios` (`ID`),
  CONSTRAINT `COMPROBANTES_ibfk_3` FOREIGN KEY (`ID_SOCIO`) REFERENCES `socios` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=648 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `comprobantes_audit`;

CREATE TABLE `comprobantes_audit` (
  `ID_AUDIT` int(8) NOT NULL AUTO_INCREMENT,
  `FECHA` datetime NOT NULL,
  `METODO` varchar(6) NOT NULL,
  `ID` int(8) NOT NULL,
  `NRO_COMPROBANTE` int(8) NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  `IMPORTE_TOTAL` double NOT NULL DEFAULT 0,
  `ID_SOCIO` int(8) NOT NULL,
  `impreso` varchar(100) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID_AUDIT`)
) ENGINE=InnoDB AUTO_INCREMENT=1342 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `impresion_comprobantes`;

CREATE TABLE `impresion_comprobantes` (
  `ID` int(8) NOT NULL AUTO_INCREMENT,
  `ID_COMPROBANTE` int(8) NOT NULL,
  `ID_ADHERENTE` int(8) NOT NULL,
  `IMPORTE` double NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ID_COMPROBANTE` (`ID_COMPROBANTE`),
  KEY `ID_ADHERENTE` (`ID_ADHERENTE`),
  KEY `ID_USUARIO_MODIFICA` (`ID_USUARIO_MODIFICA`),
  CONSTRAINT `impresion_comprobantes_ibfk_1` FOREIGN KEY (`ID_COMPROBANTE`) REFERENCES `comprobantes` (`ID`),
  CONSTRAINT `impresion_comprobantes_ibfk_2` FOREIGN KEY (`ID_ADHERENTE`) REFERENCES `adherentes` (`ID`),
  CONSTRAINT `impresion_comprobantes_ibfk_3` FOREIGN KEY (`ID_USUARIO_MODIFICA`) REFERENCES `usuarios` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `impresion_comprobantes_audit`;

CREATE TABLE `impresion_comprobantes_audit` (
  `ID_AUDIT` int(8) NOT NULL AUTO_INCREMENT,
  `FECHA` datetime NOT NULL,
  `METODO` varchar(6) NOT NULL,
  `ID` int(8) NOT NULL,
  `ID_COMPROBANTE` int(8) DEFAULT NULL,
  `ID_ADHERENTE` int(8) DEFAULT NULL,
  `IMPORTE` double DEFAULT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID_AUDIT`)
) ENGINE=InnoDB AUTO_INCREMENT=520 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `pagos`;

CREATE TABLE `pagos` (
  `ID` int(8) NOT NULL AUTO_INCREMENT,
  `VALOR` float NOT NULL,
  `ID_SOCIO` int(8) NOT NULL,
  `ID_COBRADOR` int(8) NOT NULL,
  `ID_COMPROBANTE` int(8) NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ID_SOCIO` (`ID_SOCIO`),
  KEY `ID_COBRADOR` (`ID_COBRADOR`),
  KEY `ID_COMPROBANTE` (`ID_COMPROBANTE`),
  KEY `ID_USUARIO_MODIFICA` (`ID_USUARIO_MODIFICA`),
  CONSTRAINT `PAGOS_ibfk_1` FOREIGN KEY (`ID_SOCIO`) REFERENCES `socios` (`ID`),
  CONSTRAINT `PAGOS_ibfk_2` FOREIGN KEY (`ID_COBRADOR`) REFERENCES `cobradores` (`ID`),
  CONSTRAINT `PAGOS_ibfk_3` FOREIGN KEY (`ID_COMPROBANTE`) REFERENCES `comprobantes` (`ID`),
  CONSTRAINT `PAGOS_ibfk_4` FOREIGN KEY (`ID_USUARIO_MODIFICA`) REFERENCES `usuarios` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `pagos_audit`;

CREATE TABLE `pagos_audit` (
  `ID_AUDIT` int(8) NOT NULL AUTO_INCREMENT,
  `FECHA` datetime NOT NULL,
  `METODO` varchar(6) NOT NULL,
  `ID` int(8) NOT NULL,
  `VALOR` float NOT NULL,
  `ID_SOCIO` int(8) NOT NULL,
  `ID_COBRADOR` int(8) NOT NULL,
  `ID_COMPROBANTE` int(8) NOT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID_AUDIT`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `zonas_cobradores`;

CREATE TABLE `zonas_cobradores` (
  `ID` int(8) NOT NULL AUTO_INCREMENT,
  `ID_ZONA` int(8) DEFAULT NULL,
  `ID_COBRADOR` int(8) DEFAULT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ID_ZONA` (`ID_ZONA`),
  KEY `ID_COBRADOR` (`ID_COBRADOR`),
  KEY `ID_USUARIO_MODIFICA` (`ID_USUARIO_MODIFICA`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `zonas_cobradores_audit`;

CREATE TABLE `zonas_cobradores_audit` (
  `ID_AUDIT` int(8) NOT NULL AUTO_INCREMENT,
  `FECHA` datetime NOT NULL,
  `METODO` varchar(6) NOT NULL,
  `ID` int(8) NOT NULL,
  `ID_ZONA` int(8) DEFAULT NULL,
  `ID_COBRADOR` int(8) DEFAULT NULL,
  `ID_USUARIO_MODIFICA` int(8) NOT NULL,
  PRIMARY KEY (`ID_AUDIT`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=latin1;