DELIMITER $$
	CREATE TRIGGER ADHERENTES_TRIGGER_UPDATE
	AFTER UPDATE ON ADHERENTES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ADHERENTES_AUDIT`(`FECHA`,`ID`,`DNI`,`APELLIDO`,`NOMBRE`,`DIRECCION`,`TELEFONO`,`EMAIL`,`SEXO`,`FECHA_NACIMIENTO`,`FECHA_COBERTURA`,`SALDO`,`ID_SOCIO`,`ID_ZONA`,`ID_LOCALIDAD`,`ID_OBRA_SOCIAL`,`ID_ESTADO`,`ID_USUARIO_MODIFICA`,`METODO`,`ID_ENFERMEDAD`)
	  VALUES (NOW(), NEW.ID, NEW.DNI, NEW.APELLIDO, NEW.NOMBRE, NEW.DIRECCION, NEW.TELEFONO, NEW.EMAIL, NEW.SEXO, NEW.FECHA_NACIMIENTO, NEW.FECHA_COBERTURA, NEW.SALDO, NEW.ID_SOCIO, NEW.ID_ZONA, NEW.ID_LOCALIDAD, NEW.ID_OBRA_SOCIAL, NEW.ID_ESTADO, NEW.ID_USUARIO_MODIFICA, 'UPDATE', NEW.ID_ENFERMEDAD);
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER ADHERENTES_TRIGGER_INSERT
	AFTER INSERT ON ADHERENTES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ADHERENTES_AUDIT`(`FECHA`,`ID`,`DNI`,`APELLIDO`,`NOMBRE`,`DIRECCION`,`TELEFONO`,`EMAIL`,`SEXO`,`FECHA_NACIMIENTO`,`FECHA_COBERTURA`,`SALDO`,`ID_SOCIO`,`ID_ZONA`,`ID_LOCALIDAD`,`ID_OBRA_SOCIAL`,`ID_ESTADO`,`ID_USUARIO_MODIFICA`,`METODO`,`ID_ENFERMEDAD`)
	  VALUES (NOW(), NEW.ID, NEW.DNI, NEW.APELLIDO, NEW.NOMBRE, NEW.DIRECCION, NEW.TELEFONO, NEW.EMAIL, NEW.SEXO, NEW.FECHA_NACIMIENTO, NEW.FECHA_COBERTURA, NEW.SALDO, NEW.ID_SOCIO, NEW.ID_ZONA, NEW.ID_LOCALIDAD, NEW.ID_OBRA_SOCIAL, NEW.ID_ESTADO, NEW.ID_USUARIO_MODIFICA, 'INSERT', NEW.ID_ENFERMEDAD);
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER ADHERENTES_TRIGGER_DELETE
	AFTER DELETE ON ADHERENTES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ADHERENTES_AUDIT`(`FECHA`,`ID`,`DNI`,`APELLIDO`,`NOMBRE`,`DIRECCION`,`TELEFONO`,`EMAIL`,`SEXO`,`FECHA_NACIMIENTO`,`FECHA_COBERTURA`,`SALDO`,`ID_SOCIO`,`ID_ZONA`,`ID_LOCALIDAD`,`ID_OBRA_SOCIAL`,`ID_ESTADO`,`ID_USUARIO_MODIFICA`,`METODO`,`ID_ENFERMEDAD`)
	  VALUES (NOW(), OLD.ID, OLD.DNI, OLD.APELLIDO, OLD.NOMBRE, OLD.DIRECCION, OLD.TELEFONO, OLD.EMAIL, OLD.SEXO, OLD.FECHA_NACIMIENTO, OLD.FECHA_COBERTURA, OLD.SALDO, OLD.ID_SOCIO, OLD.ID_ZONA, OLD.ID_LOCALIDAD, OLD.ID_OBRA_SOCIAL, OLD.ID_ESTADO, OLD.ID_USUARIO_MODIFICA, 'DELETE', OLD.ID_ENFERMEDAD);
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER ADHERENTES_BAJA_TRIGGER_INSERT 
	AFTER INSERT ON ADHERENTES_BAJA 
    FOR EACH ROW BEGIN
	  INSERT INTO `adherentes_baja_audit`(`FECHA`,`ID`,`ID_SOCIO`,`ID_MOTIVO_BAJA`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.ID_ADHERENTE, NEW.ID_MOTIVO_BAJA, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER;

DELIMITER $$
	CREATE TRIGGER ADHERENTES_BAJA_TRIGGER_UPDATE 
	AFTER UPDATE ON ADHERENTES_BAJA
    FOR EACH ROW BEGIN
	  INSERT INTO `adherentes_baja_audit`(`FECHA`,`ID`,`ID_SOCIO`,`ID_MOTIVO_BAJA`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.ID_ADHERENTE, NEW.ID_MOTIVO_BAJA, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;


DELIMITER $$
	CREATE TRIGGER ADHERENTES_BAJA_TRIGGER_DELETE
	AFTER DELETE ON ADHERENTES_BAJA 
    FOR EACH ROW BEGIN
	  INSERT INTO `adherentes_baja_audit`(`FECHA`,`ID`,`ID_SOCIO`,`ID_MOTIVO_BAJA`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.ID_ADHERENTE, OLD.ID_MOTIVO_BAJA, OLD.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER COBERTURA_EDADES_TRIGGER_UPDATE
	AFTER UPDATE ON COBERTURA_EDADES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `COBERTURA_EDADES_AUDIT`(`FECHA`,`ID`,`EDAD_DESDE`,`EDAD_HASTA`,`INDICADOR`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.EDAD_DESDE, NEW.EDAD_HASTA, NEW.INDICADOR, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER COBERTURA_EDADES_TRIGGER_INSERT
	AFTER INSERT ON COBERTURA_EDADES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `COBERTURA_EDADES_AUDIT`(`FECHA`,`ID`,`EDAD_DESDE`,`EDAD_HASTA`,`INDICADOR`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.EDAD_DESDE, NEW.EDAD_HASTA, NEW.INDICADOR, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER COBERTURA_EDADES_TRIGGER_DELETE
	AFTER DELETE ON COBERTURA_EDADES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `COBERTURA_EDADES_AUDIT`(`FECHA`,`ID`,`EDAD_DESDE`,`EDAD_HASTA`,`INDICADOR`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.EDAD_DESDE, OLD.EDAD_HASTA, OLD.INDICADOR, 'DELETE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER COBERTURA_ENFERMEDADES_TRIGGER_UPDATE
	AFTER UPDATE ON COBERTURA_ENFERMEDADES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `COBERTURA_ENFERMEDADES_AUDIT`(`FECHA`,`ID`,`ID_ENFERMEDAD`,`INDICADOR`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.ID_ENFERMEDAD, NEW.INDICADOR, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER COBERTURA_ENFERMEDADES_TRIGGER_INSERT
	AFTER INSERT ON COBERTURA_ENFERMEDADES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `COBERTURA_ENFERMEDADES_AUDIT`(`FECHA`,`ID`,`ID_ENFERMEDAD`,`INDICADOR`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.ID_ENFERMEDAD, NEW.INDICADOR, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER COBERTURA_ENFERMEDADES_TRIGGER_DELETE
	AFTER DELETE ON COBERTURA_ENFERMEDADES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `COBERTURA_ENFERMEDADES_AUDIT`(`FECHA`,`ID`,`ID_ENFERMEDAD`,`INDICADOR`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.ID_ENFERMEDAD, OLD.INDICADOR, 'DELETE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER COBERTURA_PESOS_TRIGGER_UPDATE
	AFTER UPDATE ON COBERTURA_PESOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `COBERTURA_PESOS_AUDIT`(`FECHA`,`ID`,`DESCRIPCION`,`PESO`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.DESCRIPCION, NEW.PESO, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER COBERTURA_PESOS_TRIGGER_INSERT
	AFTER INSERT ON COBERTURA_PESOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `COBERTURA_PESOS_AUDIT`(`FECHA`,`ID`,`DESCRIPCION`,`PESO`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.DESCRIPCION, NEW.PESO, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER COBERTURA_PESOS_TRIGGER_DELETE
	AFTER DELETE ON COBERTURA_PESOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `COBERTURA_PESOS_AUDIT`(`FECHA`,`ID`,`DESCRIPCION`,`PESO`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.DESCRIPCION, OLD.PESO, 'DELETE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER COBRADORES_TRIGGER_UPDATE
	AFTER UPDATE ON COBRADORES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `COBRADORES_AUDIT`(`FECHA`,`ID`,`DNI`,`APELLIDO`,`NOMBRE`,`DIRECCION`,`TELEFONO`,`EMAIL`,`SEXO`,`FECHA_NACIMIENTO`,`ID_LOCALIDAD`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.DNI, NEW.APELLIDO, NEW.NOMBRE, NEW.DIRECCION, NEW.TELEFONO, NEW.EMAIL, NEW.SEXO, NEW.FECHA_NACIMIENTO, NEW.ID_LOCALIDAD, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER COBRADORES_TRIGGER_INSERT
	AFTER INSERT ON COBRADORES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `COBRADORES_AUDIT`(`FECHA`,`ID`,`DNI`,`APELLIDO`,`NOMBRE`,`DIRECCION`,`TELEFONO`,`EMAIL`,`SEXO`,`FECHA_NACIMIENTO`,`ID_LOCALIDAD`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.DNI, NEW.APELLIDO, NEW.NOMBRE, NEW.DIRECCION, NEW.TELEFONO, NEW.EMAIL, NEW.SEXO, NEW.FECHA_NACIMIENTO, NEW.ID_LOCALIDAD, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER COBRADORES_TRIGGER_DELETE
	AFTER DELETE ON COBRADORES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `COBRADORES_AUDIT`(`FECHA`,`ID`,`DNI`,`APELLIDO`,`NOMBRE`,`DIRECCION`,`TELEFONO`,`EMAIL`,`SEXO`,`FECHA_NACIMIENTO`,`ID_LOCALIDAD`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.DNI, OLD.APELLIDO, OLD.NOMBRE, OLD.DIRECCION, OLD.TELEFONO, OLD.EMAIL, OLD.SEXO, OLD.FECHA_NACIMIENTO, OLD.ID_LOCALIDAD, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER COMPROBANTES_TRIGGER_UPDATE
	AFTER UPDATE ON COMPROBANTES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `COMPROBANTES_AUDIT`(`FECHA`,`ID`,`NRO_COMPROBANTE`,`ID_USUARIO_MODIFICA`,`IMPORTE_TOTAL`,`ID_SOCIO`,`IMPRESO`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NRO_COMPROBANTE, NEW.ID_USUARIO_MODIFICA, NEW.IMPORTE_TOTAL, NEW.ID_SOCIO, NEW.IMPRESO, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER COMPROBANTES_TRIGGER_INSERT
	AFTER INSERT ON COMPROBANTES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `COMPROBANTES_AUDIT`(`FECHA`,`ID`,`NRO_COMPROBANTE`,`ID_USUARIO_MODIFICA`,`IMPORTE_TOTAL`,`ID_SOCIO`,`IMPRESO`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NRO_COMPROBANTE, NEW.ID_USUARIO_MODIFICA, NEW.IMPORTE_TOTAL, NEW.ID_SOCIO, NEW.IMPRESO, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER COMPROBANTES_TRIGGER_DELETE
	AFTER DELETE ON COMPROBANTES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `COMPROBANTES_AUDIT`(`FECHA`,`ID`,`NRO_COMPROBANTE`,`ID_USUARIO_MODIFICA`,`IMPORTE_TOTAL`,`ID_SOCIO`,`IMPRESO`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.NRO_COMPROBANTE, OLD.ID_USUARIO_MODIFICA, OLD.IMPORTE_TOTAL, OLD.ID_SOCIO, OLD.IMPRESO, 'DELETE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER ENFERMEDADES_TRIGGER_UPDATE
	AFTER UPDATE ON ENFERMEDADES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ENFERMEDADES_AUDIT`(`FECHA`,`ID`,`DESCRIPCION`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.DESCRIPCION, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER ENFERMEDADES_TRIGGER_INSERT
	AFTER INSERT ON ENFERMEDADES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ENFERMEDADES_AUDIT`(`FECHA`,`ID`,`DESCRIPCION`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.DESCRIPCION, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER ENFERMEDADES_TRIGGER_DELETE
	AFTER DELETE ON ENFERMEDADES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ENFERMEDADES_AUDIT`(`FECHA`,`ID`,`DESCRIPCION`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.DESCRIPCION, 'DELETE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER ESTADOS_TRIGGER_UPDATE
	AFTER UPDATE ON ESTADOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ESTADOS_AUDIT`(`FECHA`,`ID`,`NRO_ESTADO`,`DESCRIPCION`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NRO_ESTADO, NEW.DESCRIPCION, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER ESTADOS_TRIGGER_INSERT
	AFTER INSERT ON ESTADOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ESTADOS_AUDIT`(`FECHA`,`ID`,`NRO_ESTADO`,`DESCRIPCION`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NRO_ESTADO, NEW.DESCRIPCION, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER ESTADOS_TRIGGER_DELETE
	AFTER DELETE ON ESTADOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ESTADOS_AUDIT`(`FECHA`,`ID`,`NRO_ESTADO`,`DESCRIPCION`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.NRO_ESTADO, OLD.DESCRIPCION, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER IMPRESION_COMPROBANTES_TRIGGER_UPDATE
	AFTER UPDATE ON IMPRESION_COMPROBANTES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `IMPRESION_COMPROBANTES_AUDIT`(`FECHA`,`ID`,`ID_COMPROBANTE`,`ID_ADHERENTE`,`IMPORTE`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.ID_COMPROBANTE, NEW.ID_ADHERENTE, NEW.IMPORTE, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER IMPRESION_COMPROBANTES_TRIGGER_INSERT
	AFTER INSERT ON IMPRESION_COMPROBANTES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `IMPRESION_COMPROBANTES_AUDIT`(`FECHA`,`ID`,`ID_COMPROBANTE`,`ID_ADHERENTE`,`IMPORTE`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.ID_COMPROBANTE, NEW.ID_ADHERENTE, NEW.IMPORTE, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER IMPRESION_COMPROBANTES_TRIGGER_DELETE
	AFTER DELETE ON IMPRESION_COMPROBANTES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `IMPRESION_COMPROBANTES_AUDIT`(`FECHA`,`ID`,`ID_COMPROBANTE`,`ID_ADHERENTE`,`IMPORTE`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.ID_COMPROBANTE, OLD.ID_ADHERENTE, OLD.IMPORTE, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER LOCALIDADES_TRIGGER_UPDATE
	AFTER UPDATE ON LOCALIDADES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `LOCALIDADES_AUDIT`(`FECHA`,`ID`,`NRO_LOCALIDAD`,`NOMBRE`,`CODIGO_POSTAL`,`ID_PROVINCIA`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NRO_LOCALIDAD, NEW.NOMBRE, NEW.CODIGO_POSTAL, NEW.ID_PROVINCIA, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER LOCALIDADES_TRIGGER_INSERT
	AFTER INSERT ON LOCALIDADES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `LOCALIDADES_AUDIT`(`FECHA`,`ID`,`NRO_LOCALIDAD`,`NOMBRE`,`CODIGO_POSTAL`,`ID_PROVINCIA`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NRO_LOCALIDAD, NEW.NOMBRE, NEW.CODIGO_POSTAL, NEW.ID_PROVINCIA, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER LOCALIDADES_TRIGGER_DELETE
	AFTER DELETE ON LOCALIDADES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `LOCALIDADES_AUDIT`(`FECHA`,`ID`,`NRO_LOCALIDAD`,`NOMBRE`,`CODIGO_POSTAL`,`ID_PROVINCIA`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.NRO_LOCALIDAD, OLD.NOMBRE, OLD.CODIGO_POSTAL, OLD.ID_PROVINCIA, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER MOTIVOS_BAJA_TRIGGER_UPDATE
	AFTER UPDATE ON MOTIVOS_BAJA
	FOR EACH ROW
	BEGIN
	  INSERT INTO `MOTIVOS_BAJA_AUDIT`(`FECHA`,`ID`,`DESCRIPCION`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.DESCRIPCION, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER MOTIVOS_BAJA_TRIGGER_INSERT
	AFTER INSERT ON MOTIVOS_BAJA
	FOR EACH ROW
	BEGIN
	  INSERT INTO `MOTIVOS_BAJA_AUDIT`(`FECHA`,`ID`,`DESCRIPCION`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.DESCRIPCION, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER MOTIVOS_BAJA_TRIGGER_DELETE
	AFTER DELETE ON MOTIVOS_BAJA
	FOR EACH ROW
	BEGIN
	  INSERT INTO `MOTIVOS_BAJA_AUDIT`(`FECHA`,`ID`,`DESCRIPCION`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.DESCRIPCION, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER OBRAS_SOCIALES_TRIGGER_UPDATE
	AFTER UPDATE ON OBRAS_SOCIALES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `OBRAS_SOCIALES_AUDIT`(`FECHA`,`ID`,`DESCRIPCION`,`TIENE_SEPELIO`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.DESCRIPCION, NEW.TIENE_SEPELIO, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER OBRAS_SOCIALES_TRIGGER_INSERT
	AFTER INSERT ON OBRAS_SOCIALES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `OBRAS_SOCIALES_AUDIT`(`FECHA`,`ID`,`DESCRIPCION`,`TIENE_SEPELIO`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.DESCRIPCION, NEW.TIENE_SEPELIO, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER OBRAS_SOCIALES_TRIGGER_DELETE
	AFTER DELETE ON OBRAS_SOCIALES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `OBRAS_SOCIALES_AUDIT`(`FECHA`,`ID`,`DESCRIPCION`,`TIENE_SEPELIO`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.DESCRIPCION, OLD.TIENE_SEPELIO, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER PAGOS_TRIGGER_UPDATE
	AFTER UPDATE ON PAGOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `PAGOS_AUDIT`(`FECHA`,`ID`,`VALOR`,`ID_SOCIO`,`ID_COBRADOR`,`ID_COMPROBANTE`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.VALOR, NEW.ID_SOCIO, NEW.ID_COBRADOR, NEW.ID_COMPROBANTE, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER PAGOS_TRIGGER_INSERT
	AFTER INSERT ON PAGOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `PAGOS_AUDIT`(`FECHA`,`ID`,`VALOR`,`ID_SOCIO`,`ID_COBRADOR`,`ID_COMPROBANTE`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.VALOR, NEW.ID_SOCIO, NEW.ID_COBRADOR, NEW.ID_COMPROBANTE, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER PAGOS_TRIGGER_DELETE
	AFTER DELETE ON PAGOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `PAGOS_AUDIT`(`FECHA`,`ID`,`VALOR`,`ID_SOCIO`,`ID_COBRADOR`,`ID_COMPROBANTE`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.VALOR, OLD.ID_SOCIO, OLD.ID_COBRADOR, OLD.ID_COMPROBANTE, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER PARAMETROS_EMPRESA_TRIGGER_UPDATE
	AFTER UPDATE ON PARAMETROS_EMPRESA
	FOR EACH ROW
	BEGIN
	  INSERT INTO `PARAMETROS_EMPRESA_AUDIT`(`FECHA`,`ID`,`NOMBRE`,`DIRECCION`,`CUIT`,`INICIO_ACTIVIDADES`,`CONDICION_IVA`,`CONDICION_IIBB`,`TELEFONO`,`EMAIL`,`ID_LOCALIDAD`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NOMBRE, NEW.DIRECCION, NEW.CUIT, NEW.INICIO_ACTIVIDADES, NEW.CONDICION_IVA, NEW.CONDICION_IIBB, NEW.TELEFONO, NEW.EMAIL, NEW.ID_LOCALIDAD, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER PARAMETROS_EMPRESA_TRIGGER_INSERT
	AFTER INSERT ON PARAMETROS_EMPRESA
	FOR EACH ROW
	BEGIN
	  INSERT INTO `PARAMETROS_EMPRESA_AUDIT`(`FECHA`,`ID`,`NOMBRE`,`DIRECCION`,`CUIT`,`INICIO_ACTIVIDADES`,`CONDICION_IVA`,`CONDICION_IIBB`,`TELEFONO`,`EMAIL`,`ID_LOCALIDAD`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NOMBRE, NEW.DIRECCION, NEW.CUIT, NEW.INICIO_ACTIVIDADES, NEW.CONDICION_IVA, NEW.CONDICION_IIBB, NEW.TELEFONO, NEW.EMAIL, NEW.ID_LOCALIDAD, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER PARAMETROS_EMPRESA_TRIGGER_DELETE
	AFTER DELETE ON PARAMETROS_EMPRESA
	FOR EACH ROW
	BEGIN
	  INSERT INTO `PARAMETROS_EMPRESA_AUDIT`(`FECHA`,`ID`,`NOMBRE`,`DIRECCION`,`CUIT`,`INICIO_ACTIVIDADES`,`CONDICION_IVA`,`CONDICION_IIBB`,`TELEFONO`,`EMAIL`,`ID_LOCALIDAD`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.NOMBRE, OLD.DIRECCION, OLD.CUIT, OLD.INICIO_ACTIVIDADES, OLD.CONDICION_IVA, OLD.CONDICION_IIBB, OLD.TELEFONO, OLD.EMAIL, OLD.ID_LOCALIDAD, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER PLANES_TRIGGER_UPDATE
	AFTER UPDATE ON PLANES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `PLANES_AUDIT`(`FECHA`,`METODO`,`ID`,`NRO_PLAN`,`DESCRIPCION`,`ID_USUARIO_MODIFICA`)
	  VALUES (NOW(), 'UPDATE', NEW.ID, NEW.NRO_PLAN, NEW.DESCRIPCION, NEW.ID_USUARIO_MODIFICA);
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER PLANES_TRIGGER_INSERT
	AFTER INSERT ON PLANES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `PLANES_AUDIT`(`FECHA`,`METODO`,`ID`,`NRO_PLAN`,`DESCRIPCION`,`ID_USUARIO_MODIFICA`)
	  VALUES (NOW(), 'INSERT', NEW.ID, NEW.NRO_PLAN, NEW.DESCRIPCION, NEW.ID_USUARIO_MODIFICA);
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER PLANES_TRIGGER_DELETE
	AFTER DELETE ON PLANES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `PLANES_AUDIT`(`FECHA`,`METODO`,`ID`,`NRO_PLAN`,`DESCRIPCION`,`ID_USUARIO_MODIFICA`)
	  VALUES (NOW(), 'DELETE', OLD.ID, OLD.NRO_PLAN, OLD.DESCRIPCION, OLD.ID_USUARIO_MODIFICA);
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER PROVINCIAS_TRIGGER_UPDATE
	AFTER UPDATE ON PROVINCIAS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `PROVINCIAS_AUDIT`(`FECHA`,`ID`,`NOMBRE`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NOMBRE, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER PROVINCIAS_TRIGGER_INSERT
	AFTER INSERT ON PROVINCIAS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `PROVINCIAS_AUDIT`(`FECHA`,`ID`,`NOMBRE`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NOMBRE, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER PROVINCIAS_TRIGGER_DELETE
	AFTER DELETE ON PROVINCIAS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `PROVINCIAS_AUDIT`(`FECHA`,`ID`,`NOMBRE`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.NOMBRE, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER RANGOS_TARIFAS_TRIGGER_UPDATE
	AFTER UPDATE ON RANGOS_TARIFAS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `RANGOS_TARIFAS_AUDIT`(`FECHA`,`ID`,`EDAD_DESDE`,`EDAD_HASTA`,`VALOR`,`ID_USUARIO_MODIFICA`,`ID_TARIFA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.EDAD_DESDE, NEW.EDAD_HASTA, NEW.VALOR, NEW.ID_USUARIO_MODIFICA, NEW.ID_TARIFA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER RANGOS_TARIFAS_TRIGGER_INSERT
	AFTER INSERT ON RANGOS_TARIFAS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `RANGOS_TARIFAS_AUDIT`(`FECHA`,`ID`,`EDAD_DESDE`,`EDAD_HASTA`,`VALOR`,`ID_USUARIO_MODIFICA`,`ID_TARIFA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.EDAD_DESDE, NEW.EDAD_HASTA, NEW.VALOR, NEW.ID_USUARIO_MODIFICA, NEW.ID_TARIFA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER RANGOS_TARIFAS_TRIGGER_DELETE
	AFTER DELETE ON RANGOS_TARIFAS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `RANGOS_TARIFAS_AUDIT`(`FECHA`,`ID`,`EDAD_DESDE`,`EDAD_HASTA`,`VALOR`,`ID_USUARIO_MODIFICA`,`ID_TARIFA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.EDAD_DESDE, OLD.EDAD_HASTA, OLD.VALOR, OLD.ID_USUARIO_MODIFICA, OLD.ID_TARIFA, 'DELETE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER ROLES_TRIGGER_UPDATE
	AFTER UPDATE ON ROLES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ROLES_AUDIT`(`FECHA`,`ID`,`NOMBRE`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NOMBRE, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER ROLES_TRIGGER_INSERT
	AFTER INSERT ON ROLES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ROLES_AUDIT`(`FECHA`,`ID`,`NOMBRE`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NOMBRE, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER ROLES_TRIGGER_DELETE
	AFTER DELETE ON ROLES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ROLES_AUDIT`(`FECHA`,`ID`,`NOMBRE`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.NOMBRE, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER SOCIOS_BAJA_TRIGGER_UPDATE
	AFTER UPDATE ON SOCIOS_BAJA
	FOR EACH ROW
	BEGIN
	  INSERT INTO `SOCIOS_BAJA_AUDIT`(`FECHA`,`ID`,`ID_SOCIO`,`ID_MOTIVO_BAJA`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.ID_SOCIO, NEW.ID_MOTIVO_BAJA, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER SOCIOS_BAJA_TRIGGER_INSERT
	AFTER INSERT ON SOCIOS_BAJA
	FOR EACH ROW
	BEGIN
	  INSERT INTO `SOCIOS_BAJA_AUDIT`(`FECHA`,`ID`,`ID_SOCIO`,`ID_MOTIVO_BAJA`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.ID_SOCIO, NEW.ID_MOTIVO_BAJA, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER SOCIOS_BAJA_TRIGGER_DELETE
	AFTER DELETE ON SOCIOS_BAJA
	FOR EACH ROW
	BEGIN
	  INSERT INTO `SOCIOS_BAJA_AUDIT`(`FECHA`,`ID`,`ID_SOCIO`,`ID_MOTIVO_BAJA`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.ID_SOCIO, OLD.ID_MOTIVO_BAJA, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER SOCIOS_TRIGGER_UPDATE
	AFTER UPDATE ON SOCIOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `SOCIOS_AUDIT`(`FECHA`,`ID`,`DNI`,`APELLIDO`,`NOMBRE`,`DIRECCION`,`TELEFONO`,`EMAIL`,`SEXO`,`FECHA_NACIMIENTO`,`FECHA_COBERTURA`,`SALDO`,`ID_TARIFA`,`ID_ZONA`,`ID_LOCALIDAD`,`ID_OBRA_SOCIAL`,`ID_ESTADO`,`ID_USUARIO_MODIFICA`,`ID_ENFERMEDAD`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.DNI, NEW.APELLIDO, NEW.NOMBRE, NEW.DIRECCION, NEW.TELEFONO, NEW.EMAIL, NEW.SEXO, NEW.FECHA_NACIMIENTO, NEW.FECHA_COBERTURA, NEW.SALDO, NEW.ID_TARIFA, NEW.ID_ZONA, NEW.ID_LOCALIDAD, NEW.ID_OBRA_SOCIAL, NEW.ID_ESTADO, NEW.ID_USUARIO_MODIFICA, NEW.ID_ENFERMEDAD, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER SOCIOS_TRIGGER_INSERT
	AFTER INSERT ON SOCIOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `SOCIOS_AUDIT`(`FECHA`,`ID`,`DNI`,`APELLIDO`,`NOMBRE`,`DIRECCION`,`TELEFONO`,`EMAIL`,`SEXO`,`FECHA_NACIMIENTO`,`FECHA_COBERTURA`,`SALDO`,`ID_TARIFA`,`ID_ZONA`,`ID_LOCALIDAD`,`ID_OBRA_SOCIAL`,`ID_ESTADO`,`ID_USUARIO_MODIFICA`,`ID_ENFERMEDAD`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.DNI, NEW.APELLIDO, NEW.NOMBRE, NEW.DIRECCION, NEW.TELEFONO, NEW.EMAIL, NEW.SEXO, NEW.FECHA_NACIMIENTO, NEW.FECHA_COBERTURA, NEW.SALDO, NEW.ID_TARIFA, NEW.ID_ZONA, NEW.ID_LOCALIDAD, NEW.ID_OBRA_SOCIAL, NEW.ID_ESTADO, NEW.ID_USUARIO_MODIFICA, NEW.ID_ENFERMEDAD, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER SOCIOS_TRIGGER_DELETE
	AFTER DELETE ON SOCIOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `SOCIOS_AUDIT`(`FECHA`,`ID`,`DNI`,`APELLIDO`,`NOMBRE`,`DIRECCION`,`TELEFONO`,`EMAIL`,`SEXO`,`FECHA_NACIMIENTO`,`FECHA_COBERTURA`,`SALDO`,`ID_TARIFA`,`ID_ZONA`,`ID_LOCALIDAD`,`ID_OBRA_SOCIAL`,`ID_ESTADO`,`ID_USUARIO_MODIFICA`,`ID_ENFERMEDAD`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.DNI, OLD.APELLIDO, OLD.NOMBRE, OLD.DIRECCION, OLD.TELEFONO, OLD.EMAIL, OLD.SEXO, OLD.FECHA_NACIMIENTO, OLD.FECHA_COBERTURA, OLD.SALDO, OLD.ID_TARIFA, OLD.ID_ZONA, OLD.ID_LOCALIDAD, OLD.ID_OBRA_SOCIAL, OLD.ID_ESTADO, OLD.ID_USUARIO_MODIFICA, OLD.ID_ENFERMEDAD, 'DELETE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER TARIFAS_TRIGGER_UPDATE
	AFTER UPDATE ON TARIFAS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `TARIFAS_AUDIT`(`FECHA`,`ID`,`NRO_TARIFA`,`DESCRIPCION`,`VALOR`,`ID_PLAN`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NRO_TARIFA, NEW.DESCRIPCION, NEW.VALOR, NEW.ID_PLAN, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER TARIFAS_TRIGGER_INSERT
	AFTER INSERT ON TARIFAS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `TARIFAS_AUDIT`(`FECHA`,`ID`,`NRO_TARIFA`,`DESCRIPCION`,`VALOR`,`ID_PLAN`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NRO_TARIFA, NEW.DESCRIPCION, NEW.VALOR, NEW.ID_PLAN, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER TARIFAS_TRIGGER_DELETE
	AFTER DELETE ON TARIFAS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `TARIFAS_AUDIT`(`FECHA`,`ID`,`NRO_TARIFA`,`DESCRIPCION`,`VALOR`,`ID_PLAN`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.NRO_TARIFA, OLD.DESCRIPCION, OLD.VALOR, OLD.ID_PLAN, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER USUARIOS_TRIGGER_UPDATE
	AFTER UPDATE ON USUARIOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `USUARIOS_AUDIT`(`FECHA`,`ID`,`USERNAME`,`PASSWORD`,`ID_ROL`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.USERNAME, NEW.PASSWORD, NEW.ID_ROL, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER USUARIOS_TRIGGER_INSERT
	AFTER INSERT ON USUARIOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `USUARIOS_AUDIT`(`FECHA`,`ID`,`USERNAME`,`PASSWORD`,`ID_ROL`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.USERNAME, NEW.PASSWORD, NEW.ID_ROL, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER USUARIOS_TRIGGER_DELETE
	AFTER DELETE ON USUARIOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `USUARIOS_AUDIT`(`FECHA`,`ID`,`USERNAME`,`PASSWORD`,`ID_ROL`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.USERNAME, OLD.PASSWORD, OLD.ID_ROL, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER ZONAS_COBRADORES_TRIGGER_UPDATE
	AFTER UPDATE ON ZONAS_COBRADORES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ZONAS_COBRADORES_AUDIT`(`FECHA`,`ID`,`ID_ZONA`,`ID_COBRADOR`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.ID_ZONA, NEW.ID_COBRADOR, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER ZONAS_COBRADORES_TRIGGER_INSERT
	AFTER INSERT ON ZONAS_COBRADORES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ZONAS_COBRADORES_AUDIT`(`FECHA`,`ID`,`ID_ZONA`,`ID_COBRADOR`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.ID_ZONA, NEW.ID_COBRADOR, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER ZONAS_COBRADORES_TRIGGER_DELETE
	AFTER DELETE ON ZONAS_COBRADORES
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ZONAS_COBRADORES_AUDIT`(`FECHA`,`ID`,`ID_ZONA`,`ID_COBRADOR`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.ID_ZONA, OLD.ID_COBRADOR, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER ZONAS_TRIGGER_UPDATE
	AFTER UPDATE ON ZONAS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ZONAS_AUDIT`(`FECHA`,`ID`,`NRO_ZONA`,`NOMBRE`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NRO_ZONA, NEW.NOMBRE, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER ZONAS_TRIGGER_INSERT
	AFTER INSERT ON ZONAS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ZONAS_AUDIT`(`FECHA`,`ID`,`NRO_ZONA`,`NOMBRE`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NRO_ZONA, NEW.NOMBRE, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER ZONAS_TRIGGER_DELETE
	AFTER DELETE ON ZONAS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `ZONAS_AUDIT`(`FECHA`,`ID`,`NRO_ZONA`,`NOMBRE`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.NRO_ZONA, OLD.NOMBRE, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER SERVICIOS_TRIGGER_UPDATE
	AFTER UPDATE ON SERVICIOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `SERVICIOS_AUDIT`(`FECHA`,`ID`,`NRO_SERVICIO`,`DESCRIPCION`,`VALOR`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NRO_SERVICIO, NEW.DESCRIPCION, NEW.VALOR, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER SERVICIOS_TRIGGER_INSERT
	AFTER INSERT ON SERVICIOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `SERVICIOS_AUDIT`(`FECHA`,`ID`,`NRO_SERVICIO`,`DESCRIPCION`,`VALOR`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NRO_SERVICIO, NEW.DESCRIPCION, NEW.VALOR, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER SERVICIOS_TRIGGER_DELETE
	AFTER DELETE ON SERVICIOS
	FOR EACH ROW
	BEGIN
	  INSERT INTO `SERVICIOS_AUDIT`(`FECHA`,`ID`,`NRO_SERVICIO`,`DESCRIPCION`,`VALOR`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.NRO_SERVICIO, OLD.DESCRIPCION, OLD.VALOR, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER VENTA_TRIGGER_UPDATE
	AFTER UPDATE ON VENTA
	FOR EACH ROW
	BEGIN
	  INSERT INTO `VENTA_AUDIT`(`FECHA`,`ID`,`NRO_VENTA`,`DESCRIPCION`,`ID_SERVICIO`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NRO_VENTA, NEW.DESCRIPCION, NEW.ID_SERVICIO, NEW.ID_USUARIO_MODIFICA, 'UPDATE');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER VENTA_TRIGGER_INSERT
	AFTER INSERT ON VENTA
	FOR EACH ROW
	BEGIN
	  INSERT INTO `VENTA_AUDIT`(`FECHA`,`ID`,`NRO_VENTA`,`DESCRIPCION`,`ID_SERVICIO`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), NEW.ID, NEW.NRO_VENTA, NEW.DESCRIPCION, NEW.ID_SERVICIO, NEW.ID_USUARIO_MODIFICA, 'INSERT');
	END$$
DELIMITER ;

DELIMITER $$
	CREATE TRIGGER VENTA_TRIGGER_DELETE
	AFTER DELETE ON VENTA
	FOR EACH ROW
	BEGIN
	  INSERT INTO `VENTA_AUDIT`(`FECHA`,`ID`,`NRO_VENTA`,`DESCRIPCION`,`ID_SERVICIO`,`ID_USUARIO_MODIFICA`,`METODO`)
	  VALUES (NOW(), OLD.ID, OLD.NRO_VENTA, OLD.DESCRIPCION, OLD.ID_SERVICIO, OLD.ID_USUARIO_MODIFICA, 'DELETE');
	END$$
DELIMITER ;